AppBundle\Entity\ChannelDescription:
    type: entity
    oneToOne:
        channel:
            targetEntity: Librinfo\EcommerceBundle\Entity\Channel
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: channelDescriptions
