Librinfo\VarietiesBundle\Entity\Variety:
    type: entity
    oneToMany:
        products:
            targetEntity: Librinfo\ProductBundle\Entity\Product
            mappedBy: variety
        channelDescriptions:
            targetEntity: AppBundle\Entity\ChannelDescription
            mappedBy: variety
            cascade: [ persist, remove ]
            orphanRemoval: true
