Librinfo\ProductBundle\Entity\ProductVariant:
    type: entity

    manyToOne:
        seedBatch:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            inversedBy: productVariants
