Librinfo\SeedBatchBundle\Entity\SeedBatch:
    type: entity
    oneToMany:
        productVariants:
            targetEntity: Librinfo\EcommerceBundle\Entity\ProductVariant
            mappedBy: seedBatch
