Librinfo\ProductBundle\Entity\Product:
    type: entity

    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
      name: discr
      type: string
    discriminatorMap:
      seeds: AppBundle\Entity\SeedsProduct
      other: Librinfo\ProductBundle\Entity\Product

    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: products
