Librinfo\EcommerceBundle\Entity\ProductVariant:
    type: entity

    manyToMany:
        seedBatches:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            inversedBy: productVariants
