VarietyBundle\Entity\Family:
    type: mappedSuperclass
    table: lisem_variety_family
    blast:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    oneToMany:
        genuses:
            targetEntity: VarietyBundle\Entity\GenusInterface
            mappedBy: family
            cascade: [ persist ]

    uniqueConstraints:
        lisem_variety_family_name_idx:
            columns: [ name ]
