VarietyBundle\Entity\Genus:
    type: entity
    table: lisem_variety_genus
    blast:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    manyToOne:
        family:
            targetEntity: VarietyBundle\Entity\FamilyInterface
            inversedBy: genuses
            joinColumn:
                name: family_id
            cascade: [ persist ]

    oneToMany:
        specieses:
            targetEntity: VarietyBundle\Entity\SpeciesInterface
            mappedBy: genus
            cascade: [ persist ]

    uniqueConstraints:
        lisem_variety_genus_name_idx:
            columns: [ name ]
