VarietyBundle\Entity\PlantCategory:
    type: entity
    table: lisem_variety_plant_category
    repositoryClass: VarietyBundle\Entity\Repository\PlantCategoryRepository
    fields:
        code:
            type:     string(6)
            nullable: true
    manyToMany:

        species:
            targetEntity: VarietyBundle\Entity\SpeciesInterface
            mappedBy: plant_categories

        varieties:
            targetEntity: VarietyBundle\Entity\Variety
            mappedBy: plant_categories
