VarietyBundle\Entity\Species:
    type: entity
    table: lisem_variety_species
    blast:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true
        code:
            type:     string(15)
        life_cycle:
            type:     string(10)
            nullable: true
        legal_germination_rate:
            type:     integer
            nullable: true
        germination_rate:
            type:     integer
            nullable: true
            options:
                default: 0
        seed_lifespan:
            type:     integer
            nullable: true
        raise_duration:
            type:     integer
            nullable: true
        tkw:
            type:     float
            nullable: true
        regulatory_status:
            type:     string(255)
            nullable: true
    manyToMany:
        plant_categories:
            targetEntity: VarietyBundle\Entity\PlantCategory
            inversedBy: species
            joinTable:
                name: lisem_variety_species__category
                joinColumns:
                    plant_category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    species_id:
                        referencedColumnName: id
    manyToOne:
        genus:
            targetEntity: VarietyBundle\Entity\GenusInterface
            inversedBy: specieses
            joinColumn:
                name: genus_id
            cascade: [ persist ]
        parent_species:
            targetEntity: VarietyBundle\Entity\SpeciesInterface
            inversedBy: subspecieses
            joinColumn:
                name: parent_species_id
            cascade: [ persist ]

    oneToMany:
        varieties:
            targetEntity: VarietyBundle\Entity\VarietyInterface
            mappedBy: species
            cascade: [ persist ]
        subspecieses:
            targetEntity: VarietyBundle\Entity\SpeciesInterface
            mappedBy: parent_species
            cascade: [ persist ]

    uniqueConstraints:
        lisem_variety_species_name_idx:
            columns: [ name ]
        lisem_variety_species_code_idx:
            columns: [ code ]
