
VarietyBundle\Entity\VarietyDescriptionPlant:
    type: entity
    table: lisem_variety_description_plant
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\VarietyInterface
            inversedBy: plant_descriptions
            joinColumn:
                name: variety_id
