
VarietyBundle\Entity\VarietyDescriptionCommercial:
    type: entity
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\Variety
            inversedBy: commercial_descriptions
            joinColumn:
                name: variety_id
