
VarietyBundle\Entity\VarietyDescriptionCommercial:
    type: entity
    table: lisem_variety_description_commercial
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\VarietyInterface
            inversedBy: commercial_descriptions
            joinColumn:
                name: variety_id
