
VarietyBundle\Entity\VarietyDescriptionProduction:
    type: entity
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\Variety
            inversedBy: production_descriptions
            joinColumn:
                name: variety_id
