VarietyBundle\Entity\VarietyDescriptionCulture:
    type: entity
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\Variety
            inversedBy: culture_descriptions
            joinColumn:
                name: variety_id
