
VarietyBundle\Entity\VarietyDescriptionProfessional:
    type: entity
    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\Variety
            inversedBy: professional_descriptions
            joinColumn:
                name: variety_id
