VarietyBundle\Entity\VarietyDescription:
    type: entity
    table: lisem_variety_description
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: fieldset
        type: string
    discriminatorMap:
        variety: VarietyBundle\Entity\VarietyDescription
        professional: VarietyBundle\Entity\VarietyDescriptionProfessional
        amateur: VarietyBundle\Entity\VarietyDescriptionAmateur
        production: VarietyBundle\Entity\VarietyDescriptionProduction
        commercial: VarietyBundle\Entity\VarietyDescriptionCommercial
        plant: VarietyBundle\Entity\VarietyDescriptionPlant
        culture: VarietyBundle\Entity\VarietyDescriptionCulture
        inner: VarietyBundle\Entity\VarietyDescriptionInner
    repositoryClass: VarietyBundle\Entity\Repository\VarietyDescriptionRepository
