Librinfo\SeedBatchBundle\Entity\Certification:
    type: entity
    blast:
        loggable: true
    fields:
        certificationBody:
            type: text
            column: certification_body
        certificationDate:
            type: date
            column: certification_date
        expiryDate:
            type: date
            column: expiry_date
    lifecycleCallbacks: {  }
    
    oneToOne:
        certificationType:
            targetEntity: Librinfo\SeedBatchBundle\Entity\CertificationType
            cascade: [persist]
            
