Librinfo\SeedBatchBundle\Entity\Certification:
    type: entity
    blast:
        loggable: true
    fields:
        certificationDate:
            type: date
            column: certification_date
            nullable: true
        expiryDate:
            type: date
            column: expiry_date
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        plot:
            targetEntity: Librinfo\SeedBatchBundle\Entity\Plot
            inversedBy: certifications
        certificationType:
            targetEntity: Librinfo\SeedBatchBundle\Entity\CertificationType
        certifyingBody:
            targetEntity: Librinfo\SeedBatchBundle\Entity\CertifyingBody

