Sil\Bundle\VarietyBundle\Entity\Family:
    type: entity
    table: family
    blast:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    oneToMany:
        genuses:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Genus
            mappedBy: family
            cascade: [ persist ]

    uniqueConstraints:
        family_name_idx:
            columns: [ name ]