Sil\Bundle\VarietyBundle\Entity\PlantCategory:
    type: entity
    repositoryClass: Sil\Bundle\VarietyBundle\Entity\Repository\PlantCategoryRepository
    fields:
        code:
            type:     string(6)
            nullable: true
    manyToMany:
        species:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Species
            mappedBy: plant_categories
        varieties:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Variety
            mappedBy: plant_categories   