Librinfo\SeedBatchBundle\Entity\Plot:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true

    oneToMany:
        seedBatches:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            mappedBy: plot

    manyToOne:
        producer:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            joinColumn:
                name: producer_id
                referencedColumnName: id

    uniqueConstraints:
        search_idx:
            columns: [ producer_id, code ]