Librinfo\SeedBatchBundle\Entity\Plot:
    type: entity
    
    fields:
        code:
            type:       string(255)
            nullable:   true

    oneToMany:
        seedBatches:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            mappedBy: plot

    manyToOne:
        producer:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: plots
            joinColumn:
                name: producer_id
                referencedColumnName: id
    
    manyToMany:
        certifications:
            targetEntity: Librinfo\SeedBatchBundle\Entity\Certification
            joinTable:
              name: plot_certifications
              joinColumns:
                plot_id:
                  referencedColumnName: id
              inverseJoinColumns:
                certification_id:
                  referencedColumnName: id
            cascade: [persist, remove]

    uniqueConstraints:
        search_idx:
            columns: [ producer_id, code ]