Librinfo\SeedBatchBundle\Entity\SeedBatch:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true

    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            joinColumn:
                name: variety_id
                referencedColumnName: id


