Librinfo\SeedBatchBundle\Entity\SeedFarm:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true

    oneToMany:
        seedBatches:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedBatch
            mappedBy: seedFarm