Librinfo\SeedBatchBundle\Entity\SeedBatch:
    type: entity

    fields:
        code:
            type:       string(255)
            nullable:   true
        productionYear:
            type:       integer
            nullable:   true
        # TODO: related table (GerminationTest)
        germinationRate:
            type:       float
            nullable:   true
        # TODO: related table (GerminationTest)
        germinationDate:
            type:       date
            nullable:   true
        # TODO: related table (TkwTest)
        tkwRate:
            type:       float
            nullable:   true
        # TODO: related table (TkwTest)
        tkwDate:
            type:       date
            nullable:   true


    manyToOne:
        seedFarm:
            targetEntity: Librinfo\SeedBatchBundle\Entity\SeedFarm
            joinColumn:
                name: seed_farm_id
                referencedColumnName: id
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            joinColumn:
                name: variety_id
                referencedColumnName: id
        producer:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            joinColumn:
                name: producer_id
                referencedColumnName: id
        plot:
            targetEntity: Librinfo\SeedBatchBundle\Entity\Plot
            joinColumn:
                name: seed_farm_id
                referencedColumnName: id



