
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProfessional:
    type: entity
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Variety
            inversedBy: professional_descriptions
            joinColumn:
                name: variety_id
