
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionInner:
    type: entity
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Variety
            inversedBy: inner_descriptions
            joinColumn:
                name: variety_id