# info: VarietyDescription extends GenericDescription (mapped superclass)

Sil\Bundle\VarietyBundle\Entity\VarietyDescription:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: fieldset
        type: string
    discriminatorMap:
        variety: Sil\Bundle\VarietyBundle\Entity\VarietyDescription
        professional: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProfessional
        amateur: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionAmateur
        production: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProduction
        commercial: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCommercial
        plant: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionPlant
        culture: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCulture
        inner: Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionInner
    repositoryClass: Sil\Bundle\VarietyBundle\Entity\Repository\VarietyDescriptionRepository
