Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCulture:
    type: entity
    table: lisem_variety_description_culture
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\VarietyInterface
            inversedBy: culture_descriptions
            joinColumn:
                name: variety_id
