
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionAmateur:
    type: entity
    table: lisem_variety_description_amateur
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\VarietyInterface
            inversedBy: amateur_descriptions
            joinColumn:
                name: variety_id
