
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCommercial:
    type: entity
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Variety
            inversedBy: commercial_descriptions
            joinColumn:
                name: variety_id