
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProduction:
    type: entity
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\VarietyInterface
            inversedBy: production_descriptions
            joinColumn:
                name: variety_id
