
Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionPlant:
    type: entity
    manyToOne:
        variety:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\Variety
            inversedBy: plant_descriptions
            joinColumn:
                name: variety_id
