Sil\Bundle\CRMBundle\Entity\Organism:
    type: entity

    fields:
        seedProducerCode:
            type:       string
            length:     255
            nullable:   true
        seedProducer:
            type:        boolean
            options:
                default: false

    oneToMany:
        seedBatches:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\SeedBatch
            mappedBy: producer
            cascade: [ persist, remove ]
            orphanRemoval: true
        plots:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\Plot
            mappedBy: producer
            cascade: [ persist, remove ]
            orphanRemoval: true