imports:
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.family.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.genus.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.genus_embedded.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.species.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.species_embedded.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.plant_category.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_inner.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_professional.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_amateur.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_production.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_commercial.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_plant.yml" }
    - { resource: "@SilVarietyBundle/Resources/config/admin/sil_varieties.admin.variety_description_culture.yml" }
