services:
    seedbatch.organism:
        class: Librinfo\SeedBatchBundle\Admin\OrganismAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.organism_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    seedbatch.seed_batch:
        class: Librinfo\SeedBatchBundle\Admin\SeedBatchAdminConcrete
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedBatch, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seed_batch_admin.label
                labeql_translator_strategy: librinfo_core.label.strategy.librinfo