imports:
    - { resource: admin/sil_varieties.admin.family.yml }
    - { resource: admin/sil_varieties.admin.genus.yml }
    - { resource: admin/sil_varieties.admin.genus_embedded.yml }
    - { resource: admin/sil_varieties.admin.species.yml }
    - { resource: admin/sil_varieties.admin.species_embedded.yml }
    - { resource: admin/sil_varieties.admin.variety.yml }
    - { resource: admin/sil_varieties.admin.plant_category.yml }
    - { resource: admin/sil_varieties.admin.variety_description_inner.yml }
    - { resource: admin/sil_varieties.admin.variety_description_professional.yml }
    - { resource: admin/sil_varieties.admin.variety_description_amateur.yml }
    - { resource: admin/sil_varieties.admin.variety_description_production.yml }
    - { resource: admin/sil_varieties.admin.variety_description_commercial.yml }
    - { resource: admin/sil_varieties.admin.variety_description_plant.yml }
    - { resource: admin/sil_varieties.admin.variety_description_culture.yml }
