services:
    librinfo_seedbatch.admin.organism:
        class: Librinfo\SeedBatchBundle\Admin\OrganismAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoSeedBatchBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoSeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]
            
    librinfo_seedbatch.admin.seed_producer:
        class: Librinfo\SeedBatchBundle\Admin\SeedProducerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoSeedBatchBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoSeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_seedbatch.admin.seedfarm:
        class: Librinfo\SeedBatchBundle\Admin\SeedFarmAdminConcrete
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedFarm, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seed_form_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.seedbatch:
        class: Librinfo\SeedBatchBundle\Admin\SeedBatchAdminConcrete
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedBatch, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seed_batch_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.seedbatch_embedded:
        class: Librinfo\SeedBatchBundle\Admin\SeedBatchEmbeddedAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedBatch, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seedbatch_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.plot:
        class: Librinfo\SeedBatchBundle\Admin\PlotAdminConcrete
        arguments: [~, Librinfo\SeedBatchBundle\Entity\Plot, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.plot_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.plot_embedded:
        class: Librinfo\SeedBatchBundle\Admin\PlotEmbeddedAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\Plot, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.plot_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo