services:

    librinfo_varieties.admin.family:
        class: Sil\Bundle\VarietyBundle\Admin\FamilyAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Family, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.family
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:FamilyAdmin:family_edit.html.twig ] ]

    librinfo_varieties.admin.genus:
        class: Sil\Bundle\VarietyBundle\Admin\GenusAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Genus, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.genus
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:GenusAdmin:genus_edit.html.twig ] ]

    librinfo_varieties.admin.genus_embedded:
        class: Sil\Bundle\VarietyBundle\Admin\GenusEmbeddedAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Genus, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.genus
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.species:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Species, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.species
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:SpeciesAdmin:species_edit.html.twig ] ]

    librinfo_varieties.admin.species_embedded:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Species, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.species
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Variety, SilVarietyBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
        calls:
            - [ setTemplate, [ list, SilVarietyBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, SilVarietyBundle:VarietyAdmin:edit.html.twig ] ]

    librinfo_varieties.admin.plant_category:
        class: Sil\Bundle\VarietyBundle\Admin\PlantCategoryAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\PlantCategory, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.plant_category
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:PlantCategoryAdmin:plant_category_edit.html.twig ] ]

    librinfo_varieties.admin.variety_description_inner:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionInner, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_inner
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_professional:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProfessional, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_professional
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_amateur:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionAmateur, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_amateur
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_production:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionProduction, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_production
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_commercial:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCommercial, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_commercial
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_plant:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionPlant, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_plant
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties

    librinfo_varieties.admin.variety_description_culture:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionCulture, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.VarietyBundle.admin.variety_description_culture
              label_translator_strategy: blast_core.label.strategy.librinfo_varieties
