parameters:
    librinfo:

##############
# SEED BATCH
##############

        Librinfo\SeedBatchBundle\Entity\SeedBatch:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    form_group_general:
                        '':
                            code:
                                label: librinfo.label.seed_batch_code
                            variety: ~
                            producer:
                                admin_code: librinfo_seedbatch.admin.organism
                                associated_property: producerToString
                            productionYear: ~
                            batchNumber: ~
                            plot: ~
                        form_group_germination_rate:
                            germinationRate: ~
                            germinationDate: ~
                        form_group_tkw:
                            tkw: ~
                            tkwDate: ~
                    form_tab_stocks:
                        form_group_delivery:
                            deliveryDate: ~
                            deliveryNote: ~
                            grossProducerWeight: ~
                            grossDeliveredWeight: ~
                            netScreenedWeight: ~
                            toScreenWeight: ~
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_stocks
                            - form_group_specifics

            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    form_group_general:
                        '':
                            code:
                                label: librinfo.label.seed_batch_code
                            variety:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name
                                _options:
                                    admin_code: librinfo_varieties.admin.variety
                            producer:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.organism
                            productionYear: ~
                            batchNumber: ~
                            plot:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.plot
                            description: ~
                        form_group_germination_rate:
                            germinationRate: ~
                            germinationDate: ~
                        form_group_tkw:
                            tkw: ~
                            tkwDate: ~
                    form_tab_stocks:
                        form_group_delivery:
                            deliveryDate: ~
                            deliveryNote: ~
                            grossProducerWeight: ~
                            grossDeliveredWeight: ~
                            netScreenedWeight: ~
                            toScreenWeight: ~
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_stocks
                            - form_group_specifics

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    code:
                        identifier: true
                        label: librinfo.label.seed_batch_code
                    variety: ~
                    producer:
                        admin_code: librinfo_seedbatch.admin.organism
                    productionYear: ~

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code:
                        label: librinfo.label.seed_batch_code

########
# PLOT
########

        Librinfo\SeedBatchBundle\Entity\Plot:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                remove: [vcard_uid]
                add:
                    form_group_general:
                        '':
                            code: ~
                            producer:
                                admin_code: librinfo_seedbatch.admin.organism
            Sonata\AdminBundle\Form\FormMapper:
                remove: [name, vcard_uid]
                add:
                    form_group_general:
                        '':
                            name:
                                label: librinfo.label.plot_name
                            code: ~
                            producer:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.organism

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [name, createdAt, zip, country]
                add:
                    name:
                        identifier: true
                    code: ~
                    producer:
                        admin_code: librinfo_seedbatch.admin.organism
                    city: ~
                    _options:
                        fieldsOrder: [name, code, producer, city]

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    name: ~
                    producer.name: ~

############
# ORGANISM
############

        Librinfo\SeedBatchBundle\Admin\OrganismAdminConcrete:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    show_tab_plots:
                        '':
                            plots: ~
                    show_tab_seedbatches:
                        '':
                            seedBatches: ~
                    _options:
                        tabsOrder:
                            - form_group_alert
                            - form_group_general
                            - form_group_contacts
                            - show_tab_emails
                            - show_tab_plots
                            - show_tab_seedbatches
                            - default