parameters:
    librinfo:

##############
# SEED BATCH
##############

        Librinfo\SeedBatchBundle\Entity\SeedBatch:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    form_group_general:
                        '':
                            code:
                                label: librinfo.label.seed_batch_code
                            variety: ~
                            producer:
                                admin_code: librinfo_seedbatch.admin.organism
                                associated_property: producerToString
                            productionYear: ~
                            batchNumber: ~
                            plot:
                                admin_code: librinfo_seedbatch.admin.plot
                        form_group_germination_rate:
                            germinationRate: ~
                            germinationDate: ~
                        form_group_tkw:
                            tkw: ~
                            tkwDate: ~
                    form_tab_stocks:
                        form_group_delivery:
                            deliveryDate: ~
                            deliveryNote: ~
                            grossProducerWeight: ~
                            grossDeliveredWeight: ~
                            netScreenedWeight: ~
                            toScreenWeight: ~
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_stocks
                            - form_group_specifics

            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    form_group_general:
                        '':
                            code:
                                label: librinfo.label.seed_batch_code
                            variety:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name
                                _options:
                                    admin_code: librinfo_varieties.admin.variety
                                    translation_domain: messages
                            producer:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.organism
                            productionYear: ~
                            batchNumber: ~
                            plot:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.plot
                            description: ~
                        form_group_germination_rate:
                            germinationRate: ~
                            germinationDate: ~
                        form_group_tkw:
                            tkw: ~
                            tkwDate: ~
                    form_tab_stocks:
                        form_group_delivery:
                            deliveryDate: ~
                            deliveryNote: ~
                            grossProducerWeight: ~
                            grossDeliveredWeight: ~
                            netScreenedWeight: ~
                            toScreenWeight: ~
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_stocks
                            - form_group_specifics

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    code:
                        identifier: true
                        label: librinfo.label.seed_batch_code
                    variety: ~
                    producer:
                        admin_code: librinfo_seedbatch.admin.organism
                    productionYear: ~

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code:
                        label: librinfo.label.seed_batch_code

#######################
# SEED BATCH EMBEDDED
#######################

        Librinfo\SeedBatchBundle\Admin\SeedBatchEmbeddedAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                add: ~
            Sonata\AdminBundle\Form\FormMapper:
                remove: ['*']
                add:
                    '':
                        form_group_seedbatch:
                            code:
                                label: librinfo.label.seed_batch_code
                            variety: ~
                            producer:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.organism
                            productionYear: ~
                            batchNumber: ~
                            plot:
                                _options:
                                    admin_code: librinfo_seedbatch.admin.plot_embedded
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~


########
# PLOT
########

        Librinfo\SeedBatchBundle\Entity\Plot:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                remove: [vcard_uid]
                add:
                    form_group_general:
                        '':
                            code: ~
                            producer:
                                admin_code: librinfo_seedbatch.admin.organism
            Sonata\AdminBundle\Form\FormMapper:
                remove: [name, vcard_uid]
                add:
                    form_group_general:
                        '':
                            name:
                                label: librinfo.label.plot_name
                            code: ~
                            producer:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                _options:
                                    admin_code: librinfo_seedbatch.admin.organism
                    _options:
                        tabsOrder:

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [name, createdAt, zip, country]
                add:
                    name:
                        identifier: true
                    code: ~
                    producer:
                        admin_code: librinfo_seedbatch.admin.organism
                    city: ~
                    _options:
                        fieldsOrder: [name, code, producer, city]

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    name: ~
                    producer.name: ~

##################
# PLOT (EMBEDDED)
##################

        Librinfo\SeedBatchBundle\Admin\PlotEmbeddedAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                add: ~
            Sonata\AdminBundle\Form\FormMapper:
                remove: [name, vcard_uid, description, address, zip, city, country, createdBy, createdAt, updatedAt, updatedBy, npai]
                add:
                    '':
                        form_group_plot:
                            name:
                                label: librinfo.label.plot_name
                            code: ~
                            description: ~
                            address: ~
                            zip: ~
                            city: ~
                            country: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

############
# ORGANISM
############

        Librinfo\SeedBatchBundle\Admin\OrganismAdminConcrete:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    show_tab_plots:
                        '':
                            plots:
                                admin_code: librinfo_seedbatch.admin.plot_embedded
                    show_tab_seedbatches:
                        '':
                            seedBatches:
                                admin_code: librinfo_seedbatch.admin.seedbatch_embedded
                    _options:
                        tabsOrder:
                            - form_group_alert
                            - form_group_general
                            - form_group_contacts
                            - show_tab_plots
                            - show_tab_seedbatches
                            - show_tab_emails
                            - default

            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        form_group_organism:
                            seedProducer:
                                mapped: false
                                type: checkbox
                                required: false
                            seedProducerCode:
                                type: librinfo_entitycode
                                attr:
                                    placeholder: librinfo.placeholder.seed_producer_code
                            _options:
                                fieldsOrder:
                                    - title
                                    - firstname
                                    - name
                                    - customer
                                    - customerCode
                                    - supplier
                                    - supplierCode
                                    - seedProducer
                                    - seedProducerCode
                                    - circles
                                    - category
                                    - alert
                                    - description
                                    - administrativeNumber
                                    - email
                                    - emailNpai
                                    - emailNoNewsletter
                                    - url
                    form_tab_plots:
                        '':
                            plots:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: true
                                    btn_add: false
                                required: true
                                label: false
                                only_not_new: true
                                _options:
                                    edit: inline
                                    allow_delete: true
                                    admin_code: librinfo_seedbatch.admin.plot_embedded
                    form_tab_seedbatches:
                        '':
                            seedBatches:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: true
                                    btn_add: false
                                required: true
                                label: false
                                only_not_new: true
                                _options:
                                    edit: inline
                                    allow_delete: true
                                    admin_code: librinfo_seedbatch.admin.seedbatch_embedded
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_group_contacts
                            - form_tab_plots
                            - form_tab_seedbatches
                            - form_group_specifics

            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~