services:

# ENTITY CODE GENERATORS

    sil_seed_batch.code_generator.seed_producer:
        class: Sil\Bundle\SeedBatchBundle\CodeGenerator\SeedProducerCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_seed_batch.code_generator.seed_producer%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    sil_seed_batch.code_generator.plot:
        class: Sil\Bundle\SeedBatchBundle\CodeGenerator\PlotCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_seed_batch.code_generator.plot%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    sil_seed_batch.code_generator.seed_farm:
        class: Sil\Bundle\SeedBatchBundle\CodeGenerator\SeedFarmCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_seed_batch.code_generator.seed_farm%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    sil_seed_batch.code_generator.seed_batch:
        class: Sil\Bundle\SeedBatchBundle\CodeGenerator\SeedBatchCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_seed_batch.code_generator.seed_batch%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }
