parameters:
    seed_batch.entity.certifying_body.class:        SeedBatchBundle\Entity\CertifyingBody
    seed_batch.entity.certification.class:          SeedBatchBundle\Entity\Certification
    seed_batch.entity.certification_type.class:     SeedBatchBundle\Entity\CertificationType
    seed_batch.entity.seed_farm.class:              SeedBatchBundle\Entity\SeedFarm
    seed_batch.entity.plot.class:                   SeedBatchBundle\Entity\Plot
    seed_batch.entity.seed_batch.class:             SeedBatchBundle\Entity\SeedBatch
