services:

# ENTITY CODE GENERATORS

    seed_batch.code_generator.seed_producer:
        class: SeedBatchBundle\CodeGenerator\SeedProducerCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%seed_batch.code_generator.seed_producer%', '@doctrine.orm.entity_manager', '%sil.model.crm_organism.class%']
        tags:
            - { name: blast.entity_code_generator }

    seed_batch.code_generator.plot:
        class: SeedBatchBundle\CodeGenerator\PlotCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%seed_batch.code_generator.plot%', '@doctrine.orm.entity_manager', '%seed_batch.entity.plot.class%']
        tags:
            - { name: blast.entity_code_generator }

    seed_batch.code_generator.seed_farm:
        class: SeedBatchBundle\CodeGenerator\SeedFarmCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%seed_batch.code_generator.seed_farm%', '@doctrine.orm.entity_manager', '%seed_batch.entity.seed_farm.class%']
        tags:
            - { name: blast.entity_code_generator }

    seed_batch.code_generator.seed_batch:
        class: SeedBatchBundle\CodeGenerator\SeedBatchCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%seed_batch.code_generator.seed_batch%', '@doctrine.orm.entity_manager', '%seed_batch.entity.seed_batch.class%']
        tags:
            - { name: blast.entity_code_generator }
