# Package `sllh/php-cs-fixer-styleci-bridge` is required to get it working.

preset: symfony

disabled:
  - concat_without_spaces
  - single_quote
  - short_array_syntax
  
enabled:
  - no_php4_constructor
  - concat_with_spaces
