language: php

php:
  - '7.1'
  - nightly


services:
  - postgresql
  - elasticsearch

sudo: required

cache:
  directories:
    - $HOME/bin/
    - $HOME/.composer/cache/files
    - $HOME/.npm/
    - node_modules
    

env:
  global:
    - PATH="$HOME/.local/bin:$PATH"
    - SCRIPTS_FOLDER=bin/ci-scripts
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test

notifications:
  email:
    on_success: change
    on_failure: always
    
matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TARGET=docs
    - php: '7.1'
      env: TARGET=lint
  allow_failures:
    - php: nightly
    - env: SYMFONY_DEPRECATIONS_HELPER=0

before_install:
    - if [ -x ${SCRIPTS_FOLDER}/before_install_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/before_install_${TARGET}.sh; fi;
    - if [ -x ${SCRIPTS_FOLDER}/create_travis_database_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/create_database_${TARGET}.sh; fi;
  
install:
    - if [ -x ${SCRIPTS_FOLDER}/install_${TARGET}.sh ]; then travis_retry ${SCRIPTS_FOLDER}/install_${TARGET}.sh; fi;
  
before_script:
    - if [ -x ${SCRIPTS_FOLDER}/before_script_${TARGET}.sh ]; then travis_retry travis_retry ${SCRIPTS_FOLDER}/before_script_${TARGET}.sh; fi;

script:
    - if [ -x ${SCRIPTS_FOLDER}/run_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/run_${TARGET}.sh; fi;

after_success:
    - if [ -x ${SCRIPTS_FOLDER}/after_success_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/after_success_${TARGET}.sh; fi;

after_failure:
    - if [ -x ${SCRIPTS_FOLDER}/after_failure_${TARGET}.sh ]; then ${SCRIPTS_FOLDER}/after_failure_${TARGET}.sh; fi; 
