
services:
    sil_variety.admin.species:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesAdmin
        arguments: [~, "%sil_variety.enttity.species.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.bundle.varietybundle.admin.species
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:SpeciesAdmin:species_edit.html.twig ] ]
