
services:
    sil_variety.admin.plant_category:
        class: Sil\Bundle\VarietyBundle\Admin\PlantCategoryAdmin
        arguments: [~, "%sil_variety.entity.plant_category.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.bundle.varietybundle.admin.plant_category
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:PlantCategoryAdmin:plant_category_edit.html.twig ] ]
