
services:
    sil_seed_batch.admin.certification_type:
        class: Sil\Bundle\SeedBatchBundle\Admin\CertificationTypeAdmin
        arguments: [~, Sil\Bundle\SeedBatchBundle\Entity\CertificationType, SilMediaBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: CertificationType
              label_translator_strategy: blast_core.label.strategy.sil_seedbatch
        calls:
            - [ setTemplate, [ edit, SilMediaBundle:CRUD:edit.html.twig ] ]

