
services:
    sil_varieties.admin.species:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\Species, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.VarietyBundle.admin.species
                label_translator_strategy: blast_core.label.strategy.sil_varieties
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:SpeciesAdmin:species_edit.html.twig ] ]
