
services:
    sil_seedbatch.admin.seed_producer:
        class: Sil\Bundle\SeedBatchBundle\Admin\SeedProducerAdmin
        arguments: [~, "%sil_crm.entity.organism.class%", SilSeedBatchBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.seedbatchbundle.admin.organism
                label_translator_strategy: blast_core.label.strategy.sil_seedbatch
        calls:
            - [ setTemplate, [edit, SilSeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig]]
