
services:
    sil_seed_batch.admin.certification:
        class: Sil\Bundle\SeedBatchBundle\Admin\CertificationAdmin
        arguments: [~, "%sil_seed_batch.entity.certification.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: Certification
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
