
services:
    sil_varieties.admin.variety_description_professional:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%sil_variety.enttity.variety_description_professionnal.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.VarietyBundle.admin.variety_description_professional
                label_translator_strategy: blast_core.label.strategy.sil_varieties
