
services:
    sil_varieties.admin.variety_description_commercial:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%sil_variety.enttity.variety_description_commercial.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.bundle.varietybundle.admin.variety_description_commercial
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
