
services:
    sil_variety.admin.variety:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyAdmin
        arguments: [~, "%sil_variety.enttity.variety.class%", SilVarietyBundle:VarietyCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.bundle.varietybundle.admin.variety
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ list, SilVarietyBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, SilVarietyBundle:VarietyAdmin:edit.html.twig ] ]
