
services:
    sil_varieties.admin.species_embedded:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, "%sil_variety.enttity.species.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.VarietyBundle.admin.species
                label_translator_strategy: blast_core.label.strategy.sil_varieties
