
services:
    sil_seed_batch.admin.certifying_body:
        class: Sil\Bundle\SeedBatchBundle\Admin\CertifyingBodyAdmin
        arguments: [~, Sil\Bundle\SeedBatchBundle\Entity\CertifyingBody, SilMediaBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.seedbatchbundle.admin.certifying_body
              label_translator_strategy: blast_core.label.strategy.sil_seedbatch
        calls:
            - [ setTemplate, [ edit, SilMediaBundle:CRUD:edit.html.twig ] ]

