
services:
    sil_varieties.admin.variety_description_plant:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Sil\Bundle\VarietyBundle\Entity\VarietyDescriptionPlant, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.VarietyBundle.admin.variety_description_plant
                label_translator_strategy: blast_core.label.strategy.sil_varieties
