
services:
    sil_variety.admin.variety_description_professional:
        class: Sil\Bundle\VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%sil_variety.entity.variety_description_professionnal.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.bundle.varietybundle.admin.variety_description_professional
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
