
services:
    sil_seedbatch.admin.seedbatch:
        class: Sil\Bundle\SeedBatchBundle\Admin\SeedBatchAdmin
        arguments: [~, Sil\Bundle\SeedBatchBundle\Entity\SeedBatch, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: sil.seedbatchbundle.admin.seed_batch
                label_translator_strategy: blast_core.label.strategy.sil_seedbatch
        calls:
            - [ setTemplate, [edit, SilSeedBatchBundle:SeedBatchAdmin:edit.html.twig]]

