imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: varieties.yml }
    - { resource: "@AppBundle/Resources/config/sonata.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/app/config.yml" }
    - { resource: "@BlastUtilsBundle/Resources/config/sonata.yml" }
    - { resource: "@LibrinfoMediaBundle/Resources/config/app/config.yml" }
    - { resource: "@LibrinfoEcommerceBundle/Resources/config/app/config.yml" }

parameters:
    locale: fr_FR
    currency: EUR

    # TODO : this should be configured in BaseEntities bundle :
    #doctrine.orm.metadata.yml.class: Blast\BaseEntitiesBundle\Doctrine\ORM\Driver\SearchableYamlDriver

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    translator: { fallbacks: ["%locale%"] }
    trusted_hosts:   ~
    trusted_proxies: ~
    session: ~
    session:
        handler_id: blast_doctrine_handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # TODO: move all these form themes to the bundles (not here !)
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataCoreBundle:Form:colorpicker.html.twig'
#        - 'bootstrap_3_layout.html.twig'  # is not used (?) and conflicts with Sylius forms (?)
        - 'BlastCoreBundle:Admin/Form:fields.html.twig'
        - 'BlastUtilsBundle:Form:fields.html.twig'
        - 'BlastBaseEntitiesBundle:Form:fields.html.twig'
        - 'LibrinfoMediaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller:
        enabled:  "%kernel.debug%"
        profiler: false
    bundles:
        - LibrinfoDecoratorBundle
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            BlastBaseEntitiesBundle:
                type: yml
            # Librinfo bundles
            LibrinfoVarietiesBundle:
                type: yml
            LibrinfoSeedBatchBundle:
                type: yml
            LibrinfoCRMBundle:
                type: yml
#            LibrinfoUserBundle:
#                type: yml
            LibrinfoEcommerceBundle:
                type: yml
#            FOSUserBundle:
#                type: xml
#            SonataUserBundle: ~
            # TODO: this should go in BaseEntitiesBundle
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                is_bundle: false

        dql:
            string_functions:
                ilike: Blast\DoctrinePgsqlBundle\DoctrineExtensions\Functions\Ilike

# Swiftmailer Configuration
swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            disable_delivery:  "%mailer_disable_delivery%"
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool: { type: db }
            disable_delivery:  "%mailer_disable_delivery%"

# FosUser Configuration
# Not used any more (now using SonataSyliusUser)
#fos_user:
#    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
#    firewall_name: N/A
#    user_class: Blast\BaseEntitiesBundle\Entity\GenericEntity
#    group:
#        group_class: Blast\BaseEntitiesBundle\Entity\GenericEntity
#        group_manager: sonata.user.orm.group_manager
#    service:
#        user_manager: sonata.user.orm.user_manager

sylius_taxonomy:
    driver: doctrine/orm

sylius_locale:
    locale: fr_FR

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true

# JMS serializer
jms_serializer:
    metadata:
        auto_detection: true

#Tinymce configuration
stfalcon_tinymce:
    tinymce_jquery: true
    include_jquery: false
    language: "%locale%"

# Enable BlastBaseEntitiesBundle event listeners
blast_base_entities:
    orm:
        default:
            naming: true
            guidable: true
            timestampable: true
            addressable: true
            treeable: false
            nested_treeable: true
            nameable: true
            labelable: true
            emailable: true
            descriptible: true
            searchable: true
            loggable: true
            sortable: true
            normalize: true
            syliusGuidable: true

librinfo_crm:
    Circle:
#        allow_organisms: true   # default: true
#        allow_contacts: false    # default: false
        allow_positions: false  # default: false
        app_circles:
            -
                id: 15af43f3-d41a-4b41-aca5-3e606af348d3
                code: JAP
                name: Jardiniers particuliers
                createdAt: 2017-06-16 18:00:00
            -
                id: 19c612b4-5057-4b68-9ab1-c6f037325c2a
                code: REV
                name: Revendeurs
                createdAt: 2017-06-16 18:00:00
            -
                id: 30405c5a-92ee-4307-9272-933df540207c
                code: MAR
                name: Maraichers
                createdAt: 2017-06-16 18:00:00
            -
                id: aeef530e-63d7-4c9c-9904-5bb5c0913d44
                code: PAM
                name: Producteur aromatique
                createdAt: 2017-06-16 18:00:00
            -
                id: fa1c96e1-8771-4c19-bd69-a81129c1d6e5
                code: PRP
                name: Producteur de plants
                createdAt: 2017-06-16 18:00:00
            -
                id: 8afb9575-4194-4b2b-aac7-3f80534d97a4
                code: PRF
                name: Professionnel
                createdAt: 2017-06-16 18:00:00
            -
                id: 568ced20-9356-4406-9bec-79d9a6ddb364
                code: SEM
                name: Semencier
                createdAt: 2017-06-16 18:00:00
            -
                id: d43330ff-b35e-4e9a-9386-ede38a9bac3c
                code: ASS
                name: Associations
                createdAt: 2017-06-16 18:00:00
            -
                id: 30db8307-c998-49d9-8b94-79c4ef47125c
                code: COL
                name: Collectivités territoriales
                createdAt: 2017-06-16 18:00:00

            # # SET IN vendor/libre-informatique/seed-batch-bundle/src/Resources/config/circles.yml
            # -
            #     id: a30b75b9-7e29-4184-b152-161258ba7458
            #     code: PRO
            #     name: Producteur de semences
            #     createdAt: 2017-06-16 18:00:00

            -
                id: d7418a43-0ec2-4a5f-a007-ca609266e3ca
                code: SEF
                name: Semencier fournisseur de semences
                createdAt: 2017-06-16 18:00:00
            -
                id: 24c6a133-ffa2-4546-8bfc-7c1c3b2fe5df
                code: COD
                name: Contacts divers
                createdAt: 2017-06-16 18:00:00
            -
                id: f4a3c026-6787-430f-a821-c1ca6a4a7056
                code: PRS
                name: Prestataire de services
                createdAt: 2017-06-16 18:00:00
            -
                id: b70c9588-2c17-4ccb-8bce-ae943da81d0b
                code: FOU
                name: Fournisseurs
                createdAt: 2017-06-16 18:00:00
            -
                id: 58cbfc7b-cf37-4bce-849d-43b23eff8d75
                code: PAR
                name: Partenaires
                createdAt: 2017-06-16 18:00:00
            -
                id: 34cf030b-9a84-4e79-acf6-082968b7aa16
                code: ASE
                name: Associés au capital de l'entreprise
                createdAt: 2017-06-16 18:00:00
            -
                id: c904af0e-53b0-4f84-bfec-f907873831fa
                code: ADM
                name: Administrations
                createdAt: 2017-06-16 18:00:00
            -
                id: 3046da7a-b373-4969-80cd-a06e609ec957
                code: ORC
                name: Organismes de contrôle
                createdAt: 2017-06-16 18:00:00
            -
                id: a6ffd7cc-33be-4ae6-9475-c1bc736863e5
                code: RSP
                name: Réseau semences paysannes
                createdAt: 2017-06-16 18:00:00
            -
                id: 4e319aff-0f32-4bcd-a4f0-655ce84381c8
                code: CDC
                name: Croqueurs de Carottes
                createdAt: 2017-06-16 18:00:00
            -
                id: 21f63609-f86c-43fc-a720-59d764d9bf79
                code: SAL
                name: Salariés
                createdAt: 2017-06-16 18:00:00
            -
                id: 9c401554-b5f0-4ade-9760-172e320ca25a
                code: STA
                name: Stagiaires
                createdAt: 2017-06-16 18:00:00
            -
                id: f3b959e9-9904-4de2-ae0b-fe2ede88e422
                code: PRE
                name: Presse
                createdAt: 2017-06-16 18:00:00
            -
                id: 79e7b5c1-1ab3-4ea4-8273-134493d93cd2
                code: FOI
                name: Foire
                createdAt: 2017-06-16 18:00:00
            -
                id: d31cb244-bee4-43a3-ad74-988598d49ca2
                code: ESS
                name: Essais / tests
                createdAt: 2017-06-16 18:00:00
            -
                id: 7e690a34-2a07-401b-9e49-e7f2e3d3f2c0
                code: AMI
                name: Amis médiateur
                createdAt: 2017-06-16 18:00:00
            -
                id: 37630a06-b4bd-4659-929e-b6af10d70abc
                code: SIT
                name: Site relais
                createdAt: 2017-06-16 18:00:00
#    Organism:
#        normalize:
#            city: [uppercase]   # possible values: uppercase, titlecase
#            country: [uppercase]
#    Contact:
#        normalize:
#            firstname: [titlecase]
#            name: [uppercase]
#            city: [uppercase]
#            country: [uppercase]

fos_rest:
    exception: ~

bazinga_js_translation:
    locale_fallback: fr
    active_locales:
        - fr
        - en
    default_domain:       messages
