imports:
    - { resource: config.yml }

# # Uncomment for displaying template names in html source comments
#
# twig:
#     base_template_class: Blast\CoreBundle\Twig\DebugTemplate

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]

swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            encryption: "%mailer_encryption%"
            delivery_addresses: "%mailer_delivery_addresses%"
            disable_delivery:  "%mailer_disable_delivery%"
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            encryption: "%mailer_encryption%"
            spool: { type: db }
            delivery_addresses: "%mailer_delivery_addresses%"
            disable_delivery:  "%mailer_disable_delivery%"


# lexik_translation:
#     fallback_locale: [fr]
#     managed_locales: [fr]
#     auto_cache_clean: true
#     auto_cache_clean_interval: 600
#     dev_tools:
#         enable: true
#         create_missing: true
#         file_format: yml
#     exporter:
#         use_yml_tree: true
