imports:

    # Platform Bundle

    - { resource: "@PlatformBundle/Resources/config/parameters.yml" }
    # - { resource: "@PlatformBundle/Resources/config/config.yml" }

    - { resource: "@PlatformBundle/Resources/config/admin.yml" }

    # Vendors

    - { resource: "@PlatformBundle/Resources/config/vendor/stof.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/sil.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/sonata.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/sylius.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/lexik.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/fos.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/doctrine.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/stfalcon.yml" }

    # SIL Bundles

    - { resource: "@SilSonataSyliusUserBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSonataSyliusUserBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEmailBundle/Resources/config/parameters.yml" }
    - { resource: "@SilEmailBundle/Resources/config/app/config.yml" }

    - { resource: "@SilEcommerceBundle/Resources/config/parameters.yml" }
    - { resource: "@SilEcommerceBundle/Resources/config/app/config.yml" }

    - { resource: "@SilCRMBundle/Resources/config/parameters.yml" }
    - { resource: "@SilCRMBundle/Resources/config/app/config.yml" }

    - { resource: "@SilMediaBundle/Resources/config/parameters.yml" }
    - { resource: "@SilMediaBundle/Resources/config/app/config.yml" }

    - { resource: "@SilSyliusPayboxBundle/Resources/config/parameters.yml" }
    - { resource: "@SilSyliusPayboxBundle/Resources/config/app/config.yml" }

    - { resource: "@SilUomBundle/Resources/config/app/config.yml" }

    - { resource: "@SilStockBundle/Resources/config/parameters.yml" }
    - { resource: "@SilStockBundle/Resources/config/app/config.yml" }
    - { resource: "@SilStockBundle/Resources/config/services.yml" }

    - { resource: "@SilManufacturingBundle/Resources/config/parameters.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/app/config.yml" }
    - { resource: "@SilManufacturingBundle/Resources/config/services.yml" }

    # Blast

    - { resource: "@PlatformBundle/Resources/config/vendor/blast/csv_import.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/dashboard.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/search.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/base_entities.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/menu.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/resource.yml" }
    - { resource: "@PlatformBundle/Resources/config/vendor/blast/utils.yml" }

    - { resource: "@SeedBatchBundle/Resources/config/parameters.yml" }
    - { resource: "@SeedBatchBundle/Resources/config/config.yml" }

    - { resource: "@VarietyBundle/Resources/config/parameters.yml" }
    - { resource: "@VarietyBundle/Resources/config/config.yml" }

    - { resource: "@LisemBundle/Resources/config/parameters.yml" }
    - { resource: "@LisemBundle/Resources/config/config.yml" }

    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    locale: fr_FR
    currency: EUR

framework:
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: blast_doctrine_handler
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataCoreBundle:Form:colorpicker.html.twig'
        - 'BlastCoreBundle:Admin/Form:fields.html.twig'
        - 'BlastUtilsBundle:Form:fields.html.twig'
        - 'BlastBaseEntitiesBundle:Form:fields.html.twig'
        - 'SilMediaBundle:Form:fields.html.twig'
    globals:
        sil:
            url_prefix: "%sil.url_prefix%"


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            session:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:

                    # Blast

                    BlastBaseEntitiesBundle:
                        type: yml

                    # Sil

                    SilCRMBundle:
                        type: yml
                    SilEcommerceBundle:
                        type: yml
                    SilEmailBundle:
                        type: yml
                    SilEmailCRMBundle:
                        type: yml

                    SilMediaBundle:
                        type: yml
                    SilSonataSyliusUserBundle:
                        type: yml
                    SilUomBundle:
                        type: yml
                    SilStockBundle:
                        type: yml
                        prefix: Sil\Bundle\StockBundle\Domain\Entity
                    SilManufacturingBundle:
                        type: yml
                        prefix: Sil\Bundle\ManufacturingBundle\Domain\Entity

                    # Platform

                    PlatformBundle:
                        type: yml


                    VarietyBundle:
                        type: yml

                    SeedBatchBundle:
                        type: yml

                    LisemBundle:
                        type: yml

                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                        is_bundle: false
                dql:
                    string_functions:
                        ilike: Blast\DoctrinePgsqlBundle\DoctrineExtensions\Functions\Ilike
                        concat_ws: Oro\ORM\Query\AST\Functions\String\ConcatWs
            session:
                connection: session
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false # Only one entity manager can have auto_mappping set to true
                mappings:
                    BlastDoctrineSessionBundle:
                        type: yml

# Swiftmailer Configuration
swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            delivery_addresses: "%mailer_delivery_addresses%"
            disable_delivery:  "%mailer_disable_delivery%"
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool: { type: db }
            delivery_addresses: "%mailer_delivery_addresses%"
            disable_delivery:  "%mailer_disable_delivery%"
