imports:
     - { resource: parameters.yml }
     - { resource: security.yml }
     - { resource: services.yml }

     - { resource: "@AppBundle/Resources/config/app/config.yml" }


parameters:
    locale: fr_FR
    currency: EUR

    # TODO : this should be configured in BaseEntities bundle :
    #doctrine.orm.metadata.yml.class: Blast\BaseEntitiesBundle\Doctrine\ORM\Driver\SearchableYamlDriver

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    translator: { fallbacks: ["%locale%"] }
    trusted_hosts:   ~
    trusted_proxies: ~
    session: ~
    session:
        handler_id: blast_doctrine_handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # TODO: move all these form themes to the bundles (not here !)
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataCoreBundle:Form:colorpicker.html.twig'
#        - 'bootstrap_3_layout.html.twig'  # is not used (?) and conflicts with Sylius forms (?)
        - 'BlastCoreBundle:Admin/Form:fields.html.twig'
        - 'BlastUtilsBundle:Form:fields.html.twig'
        - 'BlastBaseEntitiesBundle:Form:fields.html.twig'
        - 'LibrinfoMediaBundle:Form:fields.html.twig'
    globals:
        librinfo:
            url_prefix: "%librinfo.url_prefix%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller:
        enabled:  "%kernel.debug%"
        profiler: false
    bundles:
        - LibrinfoDecoratorBundle
        - AppBundle
        - SyliusShopBundle
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            session:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    BlastBaseEntitiesBundle:
                        type: yml
                    LibrinfoVarietiesBundle:
                        type: yml
                    LibrinfoSeedBatchBundle:
                        type: yml
                    LibrinfoCRMBundle:
                        type: yml
                    LibrinfoEcommerceBundle:
                        type: yml
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                dql:
                    string_functions:
                        ilike: Blast\DoctrinePgsqlBundle\DoctrineExtensions\Functions\Ilike
                        concat_ws: Oro\ORM\Query\AST\Functions\String\ConcatWs
            session:
                connection: session
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false # Only one entity manager can have auto_mappping set to true
                mappings:
                    BlastDoctrineSessionBundle:
                        type: yml

# Swiftmailer Configuration
swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            delivery_addresses: ['jardinenvie@lisem.eu']
            disable_delivery:  "%mailer_disable_delivery%"
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool: { type: db }
            delivery_addresses: ['jardinenvie@lisem.eu']
            disable_delivery:  "%mailer_disable_delivery%"

sylius_taxonomy:
    driver: doctrine/orm

sylius_locale:
    locale: '%locale%'

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true

# JMS serializer
jms_serializer:
    metadata:
        auto_detection: true

#Tinymce configuration
stfalcon_tinymce:
    tinymce_jquery: true
    include_jquery: false
    language: "%locale%"

# Enable BlastBaseEntitiesBundle event listeners
blast_base_entities:
    orm:
        default:
            naming: true
            guidable: true
            timestampable: true
            addressable: true
            treeable: false
            nested_treeable: true
            nameable: true
            labelable: true
            emailable: true
            descriptible: true
            searchable: true
            loggable: true
            sortable: true
            normalize: true
            syliusGuidable: true
    entity_search_indexes: ~

fos_rest:
    exception: ~

bazinga_js_translation:
    locale_fallback: fr
    active_locales:
        - fr
        - en
    default_domain:       messages

fos_js_routing:
    routes_to_expose: [ .*librinfo_.*, .*blast_utils.* ]

lexik_maintenance:
    authorized:
        query: { debugCheck: ya }
    driver:
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %cache_dir%/maintenance.lock}
    response:
        code: 503
        status: "Service Temporarily Unavailable"
# doctrine_migrations:
#     custom_template: src/Resources/tpl/migration.tpl
