imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    default_mailer: direct_mailer
    mailers:
        direct_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            delivery_addresses: ['jardinenvie@lisem.eu']
        spool_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%" # removed for gmail
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool: { type: db }
            delivery_addresses: ['jardinenvie@lisem.eu']

