
lisem:
    resource: "@LisemBundle/Resources/config/routing.yml"

platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"

sylius_admin_dashboard_redirect:
    path: /sylius-admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true
