# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    providers:
        sonata_user_provider:
            id: sylius.sonata_user_provider.email_or_name_based
        sylius_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        sylius_shop_user_provider:
            id: sylius.shop_user_provider.email_or_name_based

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Sonata firewall :

        sonata:
            switch_user: true
            context: sonata
            pattern: /admin(?:/.*)?$
            form_login:
                provider: sonata_user_provider
                login_path: sonata_sylius_user_login
                check_path: sonata_sylius_user_login_check
                failure_path: sonata_sylius_user_login
                default_target_path: sonata_admin_dashboard
                use_forward: false
                use_referer: true
            logout:
                path: sonata_sylius_user_logout
                target: sonata_sylius_user_login
            anonymous: true

        # Sylius firewalls :

        admin:
            switch_user: true
            context: admin
            pattern: /sylius-admin(?:/.*)?$
            form_login:
                provider: sylius_admin_user_provider
                login_path: sylius_admin_login
                check_path: sylius_admin_login_check
                failure_path: sylius_admin_login
                default_target_path: sylius_admin_dashboard
                use_forward: false
                use_referer: true
            logout:
                path: sylius_admin_logout
                target: sylius_admin_login
            anonymous: true

        oauth_token:
            pattern:  ^/sylius-api/oauth/v2/token
            security: false

        api:
            pattern:    ^/sylius-api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        shop:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: shop
            pattern: /*
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: sylius_shop_user_provider
                login_path: sylius_shop_login
                check_path: sylius_shop_login_check
                failure_path: sylius_shop_login
                default_target_path: sylius_shop_homepage
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout:
                path: sylius_shop_logout
                target: sylius_shop_login
            anonymous: true

    access_control:
        # Sonata access control
        - { path: ^/(css|images|js), role: IS_AUTHENTICATED_ANONYMOUSLY } # allow assets for anonymous users
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } # allow resetting password for anonymous users
#        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED } # filter entire application
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin.*", role: ROLE_SONATA_ADMIN }

        # EmailBundle tracking
        - { path: ^/tracking, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Sylius access control
        - { path: ^/sylius-shop/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sylius-shop/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sylius-shop/verify, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/sylius-shop/account.*", role: ROLE_USER }
        - { path: ^/sylius-admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sylius-admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/sylius-admin.*", role: ROLE_ADMINISTRATION_ACCESS }
        - { path: ^/sylius-api, role: ROLE_API_ACCESS }

jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: true

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           true

#    # Allows you to specify access control rules for specific methods, such
#    # as controller actions
#    method_access_control:
#        'FOSUserBundle:SecurityController:logoutAction$': 'isAuthenticated()'
