sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:

sonata_admin:
    dashboard:
        groups:
            Customers Relationship Management:
                label: CRM
                items:
                    - crm.contact
                    - crm.position
                    - crm.organism
                    - crm.circle
            Application Management:
                label: APP
                items:
                    - app.user
                    - app.group
            Development tools:
                label: DEV
                items:
                    - crm.category
                    - crm.contactphone
                    - crm.organismphone
                    - crm.role
                    - crm.contactgroup
                    - crm.position_type
    security:
        handler: librinfo.security_bundle.sonata.voter