sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:

sonata_admin:
    dashboard:
        groups:
            Customers Relationship Management:
                label: CRM
                items:
                    - crm.contact
                    - crm.organism
                    - crm.circle
            Taxonomy:
                label: Taxonomy
                items:
                    - librinfo_varieties.admin.family
                    - librinfo_varieties.admin.genus
            CRM Admin:
                label: CRM Admin
                items:
                    - crm.category
                    - crm.position_type
                    - crm.phone_type
            Application Management:
                label: APP Admin
                items:
                    - app.user
                    - app.group
            Development tools:
                label: DEV
                roles: [ROLE_SUPER_ADMIN]
                items:
                    - crm.position
                    - crm.contactphone
                    - crm.organismphone
                    - crm.role
                    - crm.contactgroup
    security:
        handler: librinfo.security_bundle.sonata.voter
    options:
        use_icheck: true
