Sil\Bundle\SeedBatchBundle\Entity\CertifyingBody:
    type: entity
    table: lisem_seed_batch_certifying_body
    fields:
        code:
            type:       string(255)
            nullable:   true
        url:
            type:       string(255)
            nullable:   true
