SeedBatchBundle\Entity\Plot:
    type: entity
    table: lisem_seed_batch_plot
    fields:
        code:
            type:       string(255)
            nullable:   true

    oneToMany:
        seedBatches:
            targetEntity: SeedBatchBundle\Entity\SeedBatch
            mappedBy: plot
        certifications:
            targetEntity: SeedBatchBundle\Entity\Certification
            mappedBy: plot
            cascade: [ persist, remove ]
            orphanRemoval: true

    manyToOne:
        producer:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: plots
            joinColumn:
                name: producer_id
                referencedColumnName: id

    uniqueConstraints:
        lisem_seed_batch_plot_search_idx:
            columns: [ producer_id, code ]
