Sil\Bundle\SeedBatchBundle\Entity\SeedFarm:
    type: entity
    table: lisem_seed_farm
    fields:
        code:
            type:       string(255)

    oneToMany:
        seedBatches:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\SeedBatch
            mappedBy: seedFarm

    uniqueConstraints:
        lisem_seed_farm_name_idx:
            columns: [ name ]
        lisem_seed_farm_code_idx:
            columns: [ code ]
