SeedBatchBundle\Entity\SeedBatch:
    type: entity
    table: lisem_seed_batch
    fields:
        code:
            type:       string(255)
            nullable:   false
        originalCode:
            type:       string(255)
            nullable:   true
        batchNumber:
            type:       integer
            nullable:   false
        productionYear:
            type:       integer
            nullable:   false
        # TODO: related table (GerminationTest)
        germinationRate:
            type:       float
            nullable:   true
        # TODO: related table (GerminationTest)
        germinationDate:
            type:       date
            nullable:   true
        # TODO: related table (TkwTest)
        tkw:
            type:       float
            nullable:   true
        # TODO: related table (TkwTest)
        tkwDate:
            type:       date
            nullable:   true
        # TODO: related table (OrganicCertification)
        certifications:
            type:       string(255)
            nullable:   true
        grossProducerWeight:
            type:       integer
            nullable:   true
        grossDeliveredWeight:
            type:       integer
            nullable:   true
        netScreenedWeight:
            type:       integer
            nullable:   true
        toScreenWeight:
            type:       integer
            nullable:   true
        deliveryDate:
            type:       date
            nullable:   true
        deliveryNote:
            type:       boolean
            nullable:   true

    manyToOne:
        seedFarm:
            targetEntity: SeedBatchBundle\Entity\SeedFarm
            inversedBy: seedBatches
            joinColumn:
                name: seed_farm_id
                referencedColumnName: id
        variety:
            targetEntity: VarietyBundle\Entity\VarietyInterface
            inversedBy: seedBatches
        producer:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: seedBatches
            joinColumn:
                name: producer_id
                referencedColumnName: id
        plot:
            targetEntity: SeedBatchBundle\Entity\Plot
            inversedBy: seedBatches
            joinColumn:
                name: plot_id
                referencedColumnName: id

    manyToMany:
        productVariants:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductVariantInterface
            inversedBy: seedBatches
            joinTable:
                name: lisem_seed_batch__product_variant
                joinColumns:
                    seedBatch_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    producVariant_id:
                        referencedColumnName: id
