services:
    lisem.admin.email:
        class: LisemBundle\Admin\EmailAdmin
        arguments: [~, "%sil.model.email.class%", SilEmailBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.email.menu_label.email
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [edit, SilEmailBundle:CRUD:email_edit.html.twig]]
            - [ setTemplate, [show, SilEmailBundle:CRUD:email_show.html.twig]]
