
services:
    lisem.admin.variety:
        class: LisemBundle\Admin\VarietyAdmin
        arguments: [~, "%sil_variety.entity.variety.class%", LisemBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.lisembundle.admin.variety
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ list, SilVarietyBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, SilVarietyBundle:VarietyAdmin:edit.html.twig ] ]
