
services:
    sil_stock.admin.operation:
        class: LisemBundle\Admin\StockOperationAdmin
        arguments: [~, "%sil_stock.entity.operation.class%", sil.stock.controller.operation]
        calls:
            - [ setOperationCodeGenerator, ["@sil.stock.code_generator.operation"]]
            - [ setMovementCodeGenerator, ["@sil.stock.code_generator.movement"]]
            - [ setLocationRepository, ["@sil.stock.repository.location"]]
            - [ setResourceRepository, ["@sil.stock.repository.operation"]]
            - [ setTemplates, [{show: SilStockBundle:OperationAdmin:show.html.twig,edit: SilStockBundle:OperationAdmin:edit.html.twig,list: SilStockBundle:OperationAdmin:list.html.twig}]]

        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.operation
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
