
services:
    seed_batch.admin.seed_producer:
        class: SeedBatchBundle\Admin\SeedProducerAdmin
        arguments: [~, "%sil_crm.entity.organism.class%", SeedBatchBundle:OrganismAdmin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.seed_batch.menu_label.organism
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [edit, SeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig]]
