
services:
    seed_batch.admin.seed_batch_embedded:
        class: SeedBatchBundle\Admin\SeedBatchEmbeddedAdmin
        arguments: [~, "%seed_batch.entity.seed_batch.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: sil.seed_batch.menu_label.seed_batch
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
