
services:
    seed_batch.admin.certification:
        class: SeedBatchBundle\Admin\CertificationAdmin
        arguments: [~, "%seed_batch.entity.certification.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.seed_batch.menu_label.certification
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
