
services:
    seed_batch.admin.seedfarm:
        class: SeedBatchBundle\Admin\SeedFarmAdmin
        arguments: [~, "%seed_batch.entity.seed_farm.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: sil.seed_batch.menu_label.seed_farm
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
