
services:
    sil_seed_batch.admin.certification_type:
        class: Sil\Bundle\SeedBatchBundle\Admin\CertificationTypeAdmin
        arguments: [~, "%sil_seed_batch.entity.certification_type.class%", SilMediaBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.seed_batch.menu_label.certification_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilMediaBundle:CRUD:edit.html.twig ] ]
