
services:
    sil_seed_batch.admin.plot:
        class: Sil\Bundle\SeedBatchBundle\Admin\PlotAdmin
        arguments: [~, "%sil_seed_batch.entity.plot.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: sil.seed_batch.menu_label.plot
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
