blast_base_entities:
    entity_search_indexes:
        Sil\Bundle\SeedBatchBundle\Entity\SeedBatch:
            fields:
                - variety
                - producer
                - code
                - batchNumber
                - productionYear
