services:
#    librinfo_libio.example:
#        class: Librinfo\LibioBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    librinfo_libio.admin.family:
        class: Librinfo\LibioBundle\Admin\FamilyAdminConcrete
        arguments: [~, Librinfo\LibioBundle\Entity\Family, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Family

    librinfo_libio.admin.genus:
        class: Librinfo\LibioBundle\Admin\GenusAdminConcrete
        arguments: [~, Librinfo\LibioBundle\Entity\Genus, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Family
