LisemBundle\Entity\ChannelDescription:
    type: entity
    table: lisem_channel_description
    blast:
        loggable: true
    fields:
        value:
            type: string
        title:
            type: string

    manyToOne:
        variety:
            targetEntity: VarietyBundle\Entity\VarietyInterface
            inversedBy: channelDescriptions
        channel:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Channel
