LisemBundle\Entity\SilEcommerceBundle\ProductVariant:
    type: entity

    manyToMany:
        seedBatches:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\SeedBatchInterface
            mappedBy: productVariants
