LisemBundle\Entity\SilEcommerceBundle\Order:
    type: entity
    table: sil_ecommerce_order
    # associationOverride:
    #
    #     shippingAddress:
    #         targetEntity: Sil\Bundle\CRMBundle\Entity\AddressInterface
    #
    #     billingAddress:
    #         targetEntity: Sil\Bundle\CRMBundle\Entity\AddressInterface
