LisemBundle\Entity\SilEcommerceBundle\ProductVariant:
    type: mappedSuperclass
    table: sil_ecommerce_product_variant
    manyToMany:
        seedBatches:
            targetEntity: SeedBatchBundle\Entity\SeedBatch
            mappedBy: productVariants
