LisemBundle\Entity\SilVarietyBundle\Variety:
    type: entity
    table: lisem_variety
    oneToMany:
        products:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductInterface
            mappedBy: variety
        channelDescriptions:
            targetEntity: LisemBundle\Entity\ChannelDescription
            mappedBy: variety
            cascade: [ persist, remove ]
            orphanRemoval: true
        seedBatches:
            targetEntity: Sil\Bundle\SeedBatchBundle\Entity\SeedBatchInterface
            mappedBy: variety

    manyToMany:
        packagings:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductOptionValueInterface
            cascade: [ persist, remove ]
            joinTable:
                name: lisem_variety__product_option_value
                joinColumns:
                    productOptionValue_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    variety_id:
                        referencedColumnName: id

        plant_categories:
            targetEntity: Sil\Bundle\VarietyBundle\Entity\PlantCategory
            inversedBy: varieties
            joinTable:
                name: lisem_variety__plant_category
                joinColumns:
                    plantCategory_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    variety_id:
                        referencedColumnName: id
