
services:
    sil_variety.admin.genus:
        class: Sil\Bundle\VarietyBundle\Admin\GenusAdmin
        arguments: [~, "%sil_variety.entity.genus.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.genus
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilVarietyBundle:GenusAdmin:genus_edit.html.twig ] ]
