
services:
    sil_variety.admin.species_embedded:
        class: Sil\Bundle\VarietyBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, "%sil_variety.entity.species.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.species
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
