
services:
    variety.admin.variety_description_production:
        class: VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%lisem.model.variety_description_production.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.variety_description_production
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
