
services:
    variety.admin.variety_description_inner:
        class: VarietyBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, "%variety.entity.variety_description_inner.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.variety_description_inner
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
