
services:
    variety.admin.genus:
        class: VarietyBundle\Admin\GenusAdmin
        arguments: [~, "%lisem.model.variety_genus.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.genus
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, VarietyBundle:GenusAdmin:genus_edit.html.twig ] ]
