
services:
    variety.admin.plant_category:
        class: VarietyBundle\Admin\PlantCategoryAdmin
        arguments: [~, "%variety.entity.plant_category.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.variety.menu_label.plant_category
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, VarietyBundle:PlantCategoryAdmin:plant_category_edit.html.twig ] ]
