# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    libio.admin.variety:
        class: AppBundle\Admin\VarietyAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, AppBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ list, LibrinfoVarietiesBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:VarietyAdmin:edit.html.twig ] ]
