# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    lisem.admin.variety:
        class: AppBundle\Admin\VarietyAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, AppBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbunle.admin.variety
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ list, LibrinfoVarietiesBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:VarietyAdmin:edit.html.twig ] ]

# ################## SEEDS PRODUCTS #########################

    lisem.admin.seeds_product:
        class: AppBundle\Admin\SeedsProductAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Product, AppBundle:SeedsProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.seeds_product
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductAdmin:edit.html.twig ] ]

    lisem.admin.seeds_product_variant:
        class: AppBundle\Admin\SeedsProductVariantAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.seeds_product_variant
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    lisem.admin.seeds_product_variant_embedded:
        class: AppBundle\Admin\SeedsProductVariantEmbeddedAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.seeds_product_variant
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp

# ################## OTHER PRODUCTS #########################

    lisem.admin.other_product:
        class: AppBundle\Admin\OtherProductAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Product, LibrinfoEcommerceBundle:ProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.other_product
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductAdmin:edit.html.twig ] ]

    lisem.admin.other_product_variant:
        class: AppBundle\Admin\OtherProductVariantAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.other_product_variant
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    lisem.admin.other_product_variant_embedded:
        class: AppBundle\Admin\OtherProductVariantEmbeddedAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.other_product_variant
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp

# ################## CHANNEL DESC #########################

    lisem.admin.channel_description:
        class: AppBundle\Admin\ChannelDescriptionAdmin
        arguments: [~, AppBundle\Entity\ChannelDescription, BlastCoreBundle:CRUD ]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.channel_description
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp

# ################## PACKAGING #########################

    lisem.admin.packaging:
        class: AppBundle\Admin\PackagingAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductOptionValue, AppBundle:PackagingCRUD ]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.appbundle.admin.packaging
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setTemplate, [ edit, AppBundle:PackagingAdmin:edit.html.twig ] ]

# ################## OVERRIDE ECOMMERCE CUSTOMER ADMIN #########################

    librinfo_ecommerce.admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Customers Relationship Management
              label: lisem.appbunle.admin.customer
              label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
        calls:
            - [ setCodeGenerator, ['@librinfo_crm.code_generator.customer']]
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    # # UNCOMMENT IF NEEDED AND UPDATE ALL blast.yml when circles property is used
    # lisem.admin.circle:
    #     class: AppBundle\Admin\CircleAdmin
    #     arguments: [~, Librinfo\CRMBundle\Entity\Circle, LibrinfoCRMBundle:CircleAdmin ]
    #     tags:
    #         - name: sonata.admin
    #           manager_type: orm
    #           group: Customers Relationship Management
    #           label: lisem.appbunle.admin.circle
    #           label_translator_strategy: blast_core.label.strategy.librinfo_lisemapp
