# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    libio.admin.variety:
        class: AppBundle\Admin\VarietyAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, AppBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ list, LibrinfoVarietiesBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:VarietyAdmin:edit.html.twig ] ]

    libio.admin.seeds_product:
        class: AppBundle\Admin\SeedsProductAdmin
        arguments: [~, AppBundle\Entity\SeedsProduct, AppBundle:SeedsProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: libio.seeds_product_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, AppBundle:SeedsProductAdmin:edit.html.twig ] ]

    libio.admin.other_product:
        class: AppBundle\Admin\OtherProductAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\Product, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: libio.other_product_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    libio.admin.seeds_product_variant:
        class: AppBundle\Admin\SeedsProductVariantAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductVariant, LibrinfoProductBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: libio.seeds_product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoProductBundle:ProductVariantAdmin:edit.html.twig ] ]

    libio.admin.other_product_variant:
        class: AppBundle\Admin\OtherProductVariantAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductVariant, LibrinfoProductBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: libio.other_product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoProductBundle:ProductVariantAdmin:edit.html.twig ] ]

    lisem.admin.channel_description:
        class: AppBundle\Admin\ChannelDescriptionAdmin
        arguments: [~, AppBundle\Entity\ChannelDescription, BlastCoreBundle:CRUD ]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: lisem.channel_description_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
