# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    blast:
        configuration:
            search:
                add:
                    - librinfo_emailcrm.admin.organism
                    - librinfo_emailcrm.admin.contact
                    - librinfo_varieties.admin.species
                    - libio.admin.variety
                    - libio.admin.seeds_product
                    - librinfo_seedbatch.admin.organism
                    - librinfo_seedbatch.admin.seedfarm
                    - librinfo_seedbatch.admin.seedbatch

###########
#  ALL
###########
        all:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    _actions: [delete]


############
# VARIETY
############

        AppBundle\Admin\VarietyAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    show_tab_channel_descriptions:
                        show_group_channel_descriptions:
                            channelDescriptions:
                                template: AppBundle:CRUD:show_field_channel_descriptions.html.twig
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_seeds_production
                            - show_tab_channel_descriptions
                            - form_tab_inner
                            - form_tab_plant
                            - form_tab_culture
                            - form_tab_commercial
                            - form_tab_production
                            - form_tab_professional
                            - form_tab_amateur
                            - form_tab_strains
                            - form_tab_images
                            - form_group_specific
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_channel_descriptions:
                        form_group_channel_descriptions:
                            channelDescriptions:
                                type: sonata_type_collection
                                by_reference: false
                                required: false
                                label: false
                                attr:
                                    class: new-line
                                    width: 100
                                _options:
                                    edit: inline
                                    inline: table
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_seeds_production
                            - form_tab_channel_descriptions
                            - form_tab_inner
                            - form_tab_plant
                            - form_tab_culture
                            - form_tab_commercial
                            - form_tab_production
                            - form_tab_professional
                            - form_tab_amateur
                            - form_tab_strains
                            - form_tab_images
                            - form_group_specific
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    _actions: [duplicate]
                add:
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

################
# SEEDS PRODUCT
################

        AppBundle\Admin\SeedsProductAdmin:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            variety:
                                admin_code: libio.admin.variety
                            _options:
                                fieldsOrder: [name, code, variety]
                    show_tab_variants:
                        '':
                            variants:
                                admin_code: libio.admin.seeds_product_variant
                    _options:
                        tabsOrder: [form_group_general, show_tab_variants, form_group_specifics]
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                remove:
                    variants: ~
                add:
                    form_group_general:
                        '':
                            variety:
                                type: sonata_type_model_autocomplete
                                property: [name, code]
                                _options:
                                    admin_code: libio.admin.variety
                            _options:
                                fieldsOrder: [variety, name, code]
                    form_tab_variants:
                        '':
                            variants:
                                type: sonata_type_collection
                                label: false
                                by_reference: false
                                type_options:
                                    btn_add: false
                                    delete_options:
                                        type: checkbox
                                        type_options:
                                            mapped: false
                                            required: false
                                required: true    # if not true, child form fields cannot be required (why ??)
                                _options:
                                    edit: inline
                                    inline: table
                                    admin_code: libio.admin.seeds_product_variant
            #LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    name: ~
                add:
                    code:
                        label: libio.label.product_code
                        identifier: true
                    variety:
                        admin_code: librinfo_varieties.admin.variety
                    _options:
                        fieldsOrder: [code, variety, available]
                    _actions:
                        variants:
                            template: 'AppBundle:SeedsProductAdmin:list__action_variants.html.twig'

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

################
# OTHER PRODUCT
################

        AppBundle\Admin\OtherProductAdmin:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    show_tab_variants:
                        '':
                            variants:
                                admin_code: libio.admin.other_product_variant

            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                remove:
                    variants: ~
                add:
                    form_tab_variants:
                        '':
                            variants:
                                type: sonata_type_collection
                                label: false
                                by_reference: false
                                type_options:
                                    btn_add: false
                                    delete_options:
                                        type: checkbox
                                        type_options:
                                            mapped: false
                                            required: false
                                required: true    # if not true, child form fields cannot be required (why ??)
                                _options:
                                    edit: inline
                                    inline: table
                                    admin_code: libio.admin.other_product_variant

            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    _actions:
                        variants:
                            template: 'AppBundle:OtherProductAdmin:list__action_variants.html.twig'

            # FILTER
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

########################
# SEEDS PRODUCT VARIANT
########################

        AppBundle\Admin\SeedsProductVariantAdmin:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            product:
                                admin_code: libio.admin.seeds_product
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            product:
                                type: sonata_type_model_autocomplete
                                property: [translations.name, code]
                                read_only: true
                                _options:
                                    admin_code: libio.admin.seeds_product
                            _options:
                                fieldsOrder: [product, name, code, price, optionValues]
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    product:
                        admin_code: libio.admin.seeds_product
                    _options:
                        fieldsOrder:
                            - code
                            - name
                            - product
                            - available
                            - price
                            - optionValues
                            - onHand
                            - onHold
                            - tracked
            # FILTER
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

########################
# OTHER PRODUCT VARIANT
########################

        AppBundle\Admin\OtherProductVariantAdmin:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            product:
                                admin_code: libio.admin.other_product
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            product:
                                type: sonata_type_model_autocomplete
                                property: [translations.name, code]
                                read_only: true
                                _options:
                                    admin_code: libio.admin.other_product
                            _options:
                                fieldsOrder: [product, name, code, price, optionValues]
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    product:
                        admin_code: libio.admin.other_product
                    _options:
                        fieldsOrder:
                            - code
                            - name
                            - product
                            - available
                            - price
                            - optionValues
                            - onHand
                            - onHold
                            - tracked
            # FILTER
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

#####################
# CHANNEL DESCRIPTION
#####################

        AppBundle\Entity\ChannelDescription:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    value: ~
                    id: ~

            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    main_tab:
                        main_group:
                            channel:
                                type: entity
                                class: AppBundle\Entity\Channel
                            value:
                                type: blast_tinymce