# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    blast:
        configuration:
            search:
                add:
                    - librinfo_emailcrm.admin.organism
                    - librinfo_emailcrm.admin.contact
                    - librinfo_varieties.admin.species
                    - libio.admin.variety
                    - libio.admin.seeds_product
                    - librinfo_seedbatch.admin.organism
                    - librinfo_seedbatch.admin.seedfarm
                    - librinfo_seedbatch.admin.seedbatch
############
# VARIETY
############

        AppBundle\Admin\VarietyAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    show_tab_channel_descriptions:
                        show_group_channel_descriptions:
                            channelDescriptions:
                                template: AppBundle:CRUD:show_field_channel_descriptions.html.twig
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_seeds_production
                            - show_tab_channel_descriptions
                            - form_tab_inner
                            - form_tab_plant
                            - form_tab_culture
                            - form_tab_commercial
                            - form_tab_production
                            - form_tab_professional
                            - form_tab_amateur
                            - form_tab_strains
                            - form_tab_images
                            - form_group_specific
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_channel_descriptions:
                        form_group_channel_descriptions:
                            channelDescriptions:
                                type: sonata_type_collection
                                by_reference: false
                                required: false
                                label: false
                                attr:
                                    class: new-line
                                    width: 100
                                _options:
                                    edit: inline
                                    inline: table
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_seeds_production
                            - form_tab_channel_descriptions
                            - form_tab_inner
                            - form_tab_plant
                            - form_tab_culture
                            - form_tab_commercial
                            - form_tab_production
                            - form_tab_professional
                            - form_tab_amateur
                            - form_tab_strains
                            - form_tab_images
                            - form_group_specific
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    _helper_links:
                        - url: https://framacalc.org/libio_validation_varietes
                          title: Framacalc de validation (Variétés)
                          class: framacalc
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

################
# SEEDS PRODUCT
################

        AppBundle\Admin\SeedsProductAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            variety:
                                admin_code: libio.admin.variety
                            packaging: ~
                            price: ~
                            _options:
                                fieldsOrder: [name, code, variety, packaging, price]
                    _options:
                        tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            variety:
                                type: sonata_type_model_autocomplete
#                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name
                                _options:
                                    admin_code: libio.admin.variety
                            packaging:
                                type: text
                                help: libio.help.packaging
                                attr:
                                    style: 'width: 100px'
                            price:
                                type: integer
                                help: libio.help.product_price
                                attr:
                                    style: 'width: 100px'
                            _options:
                                fieldsOrder: [variety, name, packaging, code, price]

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    name: ~
                add:
                    code:
                        label: libio.label.product_code
                        identifier: true
                    variety:
                        admin_code: librinfo_varieties.admin.variety
                    _options:
                        fieldsOrder: [code, variety, available]

            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

#####################
# CHANNEL DESCRIPTION
#####################

        AppBundle\Entity\ChannelDescription:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    value: ~
                    id: ~

            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    main_tab:
                        main_group:
                            channel:
                                type: entity
                                class: AppBundle\Entity\Channel
                            value:
                                type: blast_tinymce