# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    librinfo:

############
# VARIETY
############

        AppBundle\Admin\VarietyAdminConcrete:
            Sonata\AdminBundle\Show\ShowMapper:
                add: ~
            Sonata\AdminBundle\Form\FormMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~
