libio_test:
    path:     /test/{name}
    defaults: { _controller: AppBundle:Default:test }

libio_not_implemented:
    path:   /not_implemented
    defaults: { _controller: AppBundle:Default:notImplemented }

blast_core:
    resource: "@BlastCoreBundle/Resources/config/routing.yml"
    prefix:   /

blast_utils:
    resource: "@BlastUtilsBundle/Resources/config/routing.yml"

blast_base_entities:
    resource: "@BlastBaseEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

# not used any more
#librinfo_security:
#    resource: "@LibrinfoSecurityBundle/Resources/config/routing.yml"
#    prefix:   /

librinfo_decorator:
    resource: "@LibrinfoDecoratorBundle/Resources/config/routing.yml"
    prefix:   /

# not used any more
#librinfo_user:
#    resource: "@LibrinfoUserBundle/Resources/config/routing.yml"
#    prefix:   /

librinfo_varieties:
    resource: "@LibrinfoVarietiesBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_seed_batch:
    resource: "@LibrinfoSeedBatchBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_crm:
    resource: "@LibrinfoCRMBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_email:
    resource: "@LibrinfoEmailBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_email_crm:
    resource: "@LibrinfoEmailCRMBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_media:
    resource: "@LibrinfoMediaBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_ecommerce:
    resource: "@LibrinfoEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

# Security routing for SyliusUserBundle
# (defines login, logout and login_check routes)
sonata_sylius_user_security:
    resource: "@SonataSyliusUserBundle/Resources/config/routing/security.yml"
    prefix: /
