libio_not_implemented:
    path:   /admin/not_implemented
    defaults: { _controller: AppBundle:Default:notImplemented }

lisem_test_email:
    path:   /admin/lisem_test_email
    defaults: { _controller: AppBundle:Default:testEmail }

blast_core:
    resource: "@BlastCoreBundle/Resources/config/routing.yml"
    prefix: /admin

blast_utils:
    resource: "@BlastUtilsBundle/Resources/config/routing.yml"
    prefix: /admin

blast_base_entities:
    resource: "@BlastBaseEntitiesBundle/Resources/config/routing.yml"
    prefix:   /admin

# not used any more
#librinfo_security:
#    resource: "@LibrinfoSecurityBundle/Resources/config/routing.yml"
#    prefix:   /

librinfo_decorator:
    resource: "@LibrinfoDecoratorBundle/Resources/config/routing.yml"
    prefix:   /admin

# not used any more
#librinfo_user:
#    resource: "@LibrinfoUserBundle/Resources/config/routing.yml"
#    prefix:   /

librinfo_varieties:
    resource: "@LibrinfoVarietiesBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_seed_batch:
    resource: "@LibrinfoSeedBatchBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_crm:
    resource: "@LibrinfoCRMBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_email:
    resource: "@LibrinfoEmailBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_email_crm:
    resource: "@LibrinfoEmailCRMBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_media:
    resource: "@LibrinfoMediaBundle/Resources/config/routing.yml"
    prefix:   /admin

librinfo_ecommerce:
    resource: "@LibrinfoEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Security routing for SyliusUserBundle
# (defines login, logout and login_check routes)
sonata_sylius_user_security:
    resource: "@SonataSyliusUserBundle/Resources/config/routing/security.yml"
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
