lisem_not_implemented:
    path:   /%librinfo.url_prefix%/not_implemented
    defaults: { _controller: AppBundle:Default:notImplemented }

lisem_test_email:
    path:   /%librinfo.url_prefix%/lisem_test_email
    defaults: { _controller: AppBundle:Default:testEmail }

blast_core:
    resource: "@BlastCoreBundle/Resources/config/routing.yml"
    prefix: /%librinfo.url_prefix%

blast_utils:
    resource: "@BlastUtilsBundle/Resources/config/routing.yml"
    prefix: /%librinfo.url_prefix%

blast_base_entities:
    resource: "@BlastBaseEntitiesBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_decorator:
    resource: "@LibrinfoDecoratorBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_varieties:
    resource: "@LibrinfoVarietiesBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_seed_batch:
    resource: "@LibrinfoSeedBatchBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_crm:
    resource: "@LibrinfoCRMBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_email:
    resource: "@LibrinfoEmailBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_email_crm:
    resource: "@LibrinfoEmailCRMBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_media:
    resource: "@LibrinfoMediaBundle/Resources/config/routing.yml"
    prefix:   /%librinfo.url_prefix%

librinfo_ecommerce:
    resource: "@LibrinfoEcommerceBundle/Resources/config/routing.yml"
    prefix:   / #Must not be set because of sylius route override

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /%librinfo.url_prefix%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%librinfo.url_prefix%

# Security routing for SyliusUserBundle
# (defines login, logout and login_check routes)
sonata_sylius_user_security:
    resource: "@SonataSyliusUserBundle/Resources/config/routing/security.yml"
    prefix: /%librinfo.url_prefix%

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
