# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    # CUSTOM SIDEBAR MENUS

    libio.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    libio.sidebar_menu.paremeters:
        class: Knp\Menu\MenuItem                                  # the service definition requires setting the class
        factory: ["@libio.menu_builder", createParametersSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: parameters_sidebar_menu }   # The alias is what is used to retrieve the menu
