# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

### CUSTOM SIDEBAR MENUS ###

    libio.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    libio.sidebar_menu.paremeters:
        class: Knp\Menu\MenuItem                                  # the service definition requires setting the class
        factory: ["@libio.menu_builder", createParametersSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: parameters_sidebar_menu }   # The alias is what is used to retrieve the menu

#### SYLIUS CHECKERS ####

    lisem.checker.product_variants_parity:
        class: AppBundle\Checker\ProductVariantsParityChecker

#### SYLIUS GENERATORS ####

    lisem.generator.product_variant:
        class: AppBundle\Generator\ProductVariantGenerator
        arguments:
            - "@sylius.factory.product_variant"
            - "@lisem.checker.product_variants_parity"

### SYLIUS FIXTURE FACTORIES ###

    lisem.fixture.example_factory.product:
        class: AppBundle\DataFixtures\Sylius\Factory\ProductExampleFactory
        arguments:
            - "@sylius.factory.product"
            - "@sylius.factory.product_variant"
            - "@lisem.generator.product_variant"
            - "@sylius.factory.product_attribute_value"
            - "@sylius.factory.product_image"
            - "@sylius.image_uploader"
            - "@sylius.generator.slug"
            - "@sylius.repository.taxon"
            - "@sylius.repository.product_attribute"
            - "@sylius.repository.product_option"
            - "@sylius.repository.channel"
            - "@sylius.repository.locale"
            - "@librinfo_ecommerce.code_generator.product_variant"

### SYLIUS FIXTURES ###

    lisem.fixture.product:
        class: AppBundle\DataFixtures\Sylius\ProductFixture
        arguments:
            - "@sylius.manager.product"
            - "@lisem.fixture.example_factory.product"
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.tshirt_product:
        class: AppBundle\DataFixtures\Sylius\TshirtProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@sylius.fixture.product_attribute"
            - "@sylius.fixture.product_option"
            - "@lisem.fixture.product"
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.book_product:
        class: AppBundle\DataFixtures\Sylius\BookProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@sylius.fixture.product_attribute"
            - "@lisem.fixture.product"
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.seeds_product:
        class: AppBundle\DataFixtures\Sylius\SeedsProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@lisem.fixture.product"
            - "@doctrine.orm.entity_manager"  # for Varieties
        tags:
            - { name: sylius_fixtures.fixture }


### SYLIUS THEMES ###

    lisem.theme.context.channel_based:
        class: AppBundle\Theme\ChannelBasedThemeContext
        arguments:
            - "@sylius.context.channel"
            - "@sylius.repository.theme"


#### FORMS ####

    app.form.extension.customer_profile:
        class: AppBundle\Form\Extension\CustomerProfileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType }
