# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

### CUSTOM SIDEBAR MENUS ###

    libio.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    libio.sidebar_menu.paremeters:
        class: Knp\Menu\MenuItem                                  # the service definition requires setting the class
        factory: ["@libio.menu_builder", createParametersSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: parameters_sidebar_menu }   # The alias is what is used to retrieve the menu

### SYLIUS FIXTURE FACTORIES ###

    lisem.fixture.example_factory.seeds_product:
        class: AppBundle\DataFixtures\Sylius\Factory\ProductExampleFactory
        arguments:
            - "@sylius.factory.product"
            - "@sylius.factory.product_variant"
            - "@sylius.generator.product_variant"
            - "@sylius.factory.product_attribute_value"
            - "@sylius.factory.product_image"
            - "@sylius.image_uploader"
            - "@sylius.generator.slug"
            - "@sylius.repository.taxon"
            - "@sylius.repository.product_attribute"
            - "@sylius.repository.product_option"
            - "@sylius.repository.channel"
            - "@sylius.repository.locale"

### SYLIUS FIXTURES ###

    lisem.fixture.channel:
        class: AppBundle\DataFixtures\Sylius\ChannelFixture
        arguments: ["@sylius.manager.channel", "@sylius.fixture.example_factory.channel"]
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.payment_method:
        class: AppBundle\DataFixtures\Sylius\PaymentMethodFixture
        arguments: ["@sylius.manager.payment_method", "@sylius.fixture.example_factory.payment_method"]
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.tshirt_product:
        class: AppBundle\DataFixtures\Sylius\TshirtProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@sylius.fixture.product_attribute"
            - "@sylius.fixture.product_option"
            - "@sylius.fixture.product"
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.book_product:
        class: AppBundle\DataFixtures\Sylius\BookProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@sylius.fixture.product_attribute"
            - "@sylius.fixture.product"
        tags:
            - { name: sylius_fixtures.fixture }

    lisem.fixture.seeds_product:
        class: AppBundle\DataFixtures\Sylius\SeedsProductFixture
        arguments:
            - "@sylius.fixture.taxon"
            - "@sylius.fixture.product"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sylius_fixtures.fixture }

#### FORMS ####

    app.form.extension.customer_profile:
        class: AppBundle\Form\Extension\CustomerProfileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType }
