sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
        librinfo.email.block.emails_list: ~  # TODO: put this in Email bundle
#        sonata.admin.block.menu:

sonata_admin:
    dashboard:
        groups:
            Customers Relationship Management:
                label: librinfo.menu_label.crm
                items:
                    - librinfo_seedbatch.admin.organism
                    - route:        admin_librinfo_seedbatch_organism_list
                      route_params: { 'filter[customer][value]': 1 }
                      label:        librinfo.menu_label.customers
                    - route:        admin_librinfo_seedbatch_organism_list
                      route_params: { 'filter[supplier][value]': 1 }
                      label:        librinfo.menu_label.suppliers
                    - librinfo_emailcrm.admin.contact
                    - librinfo_email.admin.email
            Varieties:
                label: ~
                on_top: true
                items:
                    - librinfo_varieties.admin.variety
            Plots:
                label: librinfo.menu_label.plots
                on_top: true
                items:
                    - librinfo_seedbatch.admin.plot
            Seed Batches:
                label: librinfo.menu_label.seed_batches
                on_top: true
                items:
                    - librinfo_seedbatch.admin.seedbatch
            CRM Admin:
                label: librinfo.menu_label.crm_admin
                items:
                    - crm.circle
                    - crm.category
                    - crm.position_type
                    - crm.phone_type
            Variety Admin:
                label: librinfo.menu_label.variety_admin
                items:
                    - librinfo_varieties.admin.family
                    - librinfo_varieties.admin.genus
                    - librinfo_varieties.admin.species
            Application Management:
                label: librinfo.menu_label.app_admin
                items:
                    - app.user
                    - app.group
#            Development tools:
#                label: DEV
#                roles: [ROLE_SUPER_ADMIN]
#                items:
#                    - crm.position
#                    - crm.contactphone
#                    - crm.organismphone
#                    - crm.role
#                    - crm.contactgroup
#                    - librinfo_varieties.admin.variety_description
    security:
        handler: librinfo.security_bundle.sonata.voter
    options:
        use_icheck: true
