sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
        librinfo.email.block.emails_list: ~  # TODO: put this in Email bundle
#        sonata.admin.block.menu:

sonata_admin:
    dashboard:
        groups:
            Customers Relationship Management:
                label: libio.menu_label.crm
                icon:  '<i class="fa fa-address-card"></i>'
                items:
                    - route: admin_librinfo_seedbatch_organism_list
                      label: libio.menu_label.organisms_list
                    - route: admin_librinfo_seedbatch_organism_create
                      label: libio.menu_label.create_organism
                    - route: admin_librinfo_emailcrm_contact_list
                      label: libio.menu_label.contacts_list
                    - route: admin_librinfo_emailcrm_contact_create
                      label: libio.menu_label.create_contact
                    - route: admin_librinfo_email_email_list
                      label: libio.menu_label.emails_list
                    - route: admin_librinfo_email_email_create
                      label: libio.menu_label.create_email
            Varieties:
                label: libio.menu_label.varieties
                icon:  '<i class="fa fa-pagelines"></i>'
                items:
                    - route: admin_libio_variety_list
                      label: libio.menu_label.varieties_list
                    - route: admin_libio_variety_create
                      label: libio.menu_label.create_variety
                    - route: admin_librinfo_varieties_species_list
                      label: libio.menu_label.species_list
                    - route: admin_librinfo_varieties_species_create
                      label: libio.menu_label.create_species
            Seed Batches:
                label: libio.menu_label.seed_batches
                icon:  '<i class="fa fa-shopping-bag"></i>'
                items:
                    - route: admin_librinfo_seedbatch_seedbatch_list
                      label: libio.menu_label.seed_batches_list
                    - route: admin_librinfo_seedbatch_seedbatch_create
                      label: libio.menu_label.create_seed_batch
                    - label: libio.menu_label.producers_list
                      route: admin_librinfo_seedbatch_seedProducer_list
                    - label: libio.menu_label.create_producer
                      route: admin_librinfo_seedbatch_seedProducer_create
                    - route: admin_librinfo_seedbatch_plot_list
                      label: libio.menu_label.plots_list
                    - route: admin_librinfo_seedbatch_plot_create
                      label: libio.menu_label.create_plot
                    - route: admin_librinfo_seedbatch_certification_list
                      label: libio.menu_label.certifications_list
                    - route: admin_librinfo_seedbatch_certification_create
                      label: libio.menu_label.create_certification
                    - label: libio.menu_label.germination_tests
                      route: libio_not_implemented
            Products:
                label: libio.menu_label.products
                icon:  '<i class="fa fa-cube"></i>'
                items:
                    - route: admin_libio_seeds_product_list
                      label: libio.menu_label.seed_products_list
                    - route: admin_libio_seeds_product_create
                      label: libio.menu_label.create_seed_product
                    - label: libio.menu_label.other_products_list
                      route: admin_libio_other_product_list
                    - label: libio.menu_label.create_other_product
                      route: admin_libio_other_product_create
                    - label: libio.menu_label.packagings
                      route: libio_not_implemented
                    - label: libio.menu_label.inventory
                      route: libio_not_implemented
                    - label: libio.menu_label.catalogs
                      route: libio_not_implemented
            Orders:
                label: libio.menu_label.orders
                icon:  '<i class="fa fa-shopping-cart"></i>'
                items:
                    - label: libio.menu_label.orders_list
                      route: libio_not_implemented
                    - label: libio.menu_label.create_order
                      route: libio_not_implemented
                    - label: libio.menu_label.customers_list
                      route: admin_librinfo_crm_customer_list
                    - label: libio.menu_label.create_customer
                      route: admin_librinfo_crm_customer_create
            Accounting:
                label: libio.menu_label.accounting
                icon:  '<i class="fa fa-balance-scale"></i>'
                items:
                    - label: libio.menu_label.sales_journal
                      route: libio_not_implemented
                    - label: libio.menu_label.cash_book
                      route: libio_not_implemented
            App settings:
                provider: parameters_sidebar_menu
                icon:     '<i class="fa fa-sliders"></i>'
#            Development tools:
#                label: DEV
#                roles: [ROLE_SUPER_ADMIN]
#                items:
#                    - crm.position
#                    - crm.contactphone
#                    - crm.organismphone
#                    - crm.role
#                    - crm.contactgroup
#                    - librinfo_varieties.admin.variety_description
    security:
        handler: librinfo.security_bundle.sonata.voter
    options:
        use_icheck: true
