imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SonataSyliusUserBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@LibrinfoEcommerceBundle/Resources/config/app/config.yml" }
    - { resource: "@AppBundle/Resources/config/sylius-fixtures.yml" }
    - { resource: "@AppBundle/Resources/config/grids.yml" }

sylius_channel:
    driver: doctrine/orm
    resources:
        channel:
            classes:
                model: AppBundle\Entity\Channel

sylius_money:
    locale: fr
    currency: EUR

sylius_theme:
    sources:
        filesystem:
            enabled: true
            filename: composer.json
            directories:
                - "%kernel.root_dir%/themes"
    context: lisem.theme.context.channel_based       # theme context service id

librinfo_ecommerce:
    code_generator:
        product_variant: AppBundle\CodeGenerator\ProductVariantCodeGenerator

payum:
    gateways:
        paybox:
            factory: paybox
            site: 1999888
            rang: 32
            identifiant: 3
            hmac: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
            sandbox: true
