imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yml" }

    - { resource: "@LibrinfoProductBundle/Resources/config/app/config.yml" }

sylius_resource:
    resources:
        app.seeds_product:
            classes:
                model: AppBundle\Entity\SeedsProduct
