imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yml" }

    - { resource: "@LibrinfoProductBundle/Resources/config/app/config.yml" }

knp_doctrine_behaviors:
    tree: true
    # all other doctrine behaviours are disabled by default
