parameters:
    lisem.model.variety_description_plant.class:            VarietyBundle\Entity\VarietyDescriptionPlant
    lisem.model.variety_description_professionnal.class:    VarietyBundle\Entity\VarietyDescriptionProfessional
    lisem.model.variety_description_production.class:       VarietyBundle\Entity\VarietyDescriptionProduction
    lisem.model.variety_description_amateur.class:          VarietyBundle\Entity\VarietyDescriptionAmateur
    lisem.model.variety_description_culture.class:          VarietyBundle\Entity\VarietyDescriptionCulture
    lisem.model.variety_description_inner.class:            VarietyBundle\Entity\VarietyDescriptionInner
    lisem.model.variety_description_commercial.class:       VarietyBundle\Entity\VarietyDescriptionCommercial
    lisem.model.variety_plant_category.class:                       VarietyBundle\Entity\PlantCategory
    lisem.model.variety_family.class:                               VarietyBundle\Entity\Family
    lisem.model.variety.class:                              VarietyBundle\Entity\Variety
    lisem.model.variety_species.class:                              VarietyBundle\Entity\Species
    lisem.model.variety_genus.class:                                VarietyBundle\Entity\Genus
