services:

# SYMFONY CUSTOM FORM TYPES

    variety.form.type.life_cycle:
        class: VarietyBundle\Form\Type\LifeCycleType
        tags:
            - { name: form.type, alias: variety_lifecycle }

    variety.form.type.variety_description:
        class: VarietyBundle\Form\Type\VarietyDescriptionType
        tags:
            - { name: form.type, alias: variety_description }
        arguments: [ '@doctrine.orm.entity_manager' ]

    variety.form.type.variety_description_filter:
        class: VarietyBundle\Form\Type\VarietyDescriptionFilterType
        tags:
            - { name: form.type, alias: variety_description_filter }
        arguments: [ '@doctrine.orm.entity_manager' ]

# FILTERS

    variety.filter.type.variety_description_filter:
        class: VarietyBundle\Filter\VarietyDescriptionFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_variety_description }

# ENTITY CODE GENERATORS

    variety.code_generator.species:
        class: VarietyBundle\CodeGenerator\SpeciesCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%variety.code_generator.species%', '@doctrine.orm.entity_manager', '%lisem.model.variety_species.class%']
        tags:
            - { name: blast.entity_code_generator }

    variety.code_generator.variety:
        class: VarietyBundle\CodeGenerator\VarietyCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%variety.code_generator.variety%', '@doctrine.orm.entity_manager', '%lisem.model.variety.class%']
        tags:
            - { name: blast.entity_code_generator }

    variety.twig.variety_description:
        class: VarietyBundle\Twig\VarietyDescription
        calls:
            - [setVarietyConfig, ['%variety%']]
            - [setTranslator, ['@translator']]
        tags:
            - { name: twig.extension }
