parameters:
    sil.model.ecommerce_product.class:                 LisemBundle\Entity\SilEcommerceBundle\Product
    sil.model.ecommerce_order.class:                   LisemBundle\Entity\SilEcommerceBundle\Order
    sil.model.ecommerce_product_variant.class:         LisemBundle\Entity\SilEcommerceBundle\ProductVariant
    sil.model.ecommerce_product_option_value.class:    LisemBundle\Entity\SilEcommerceBundle\ProductOptionValue

    lisem.model.channel_description.class:             LisemBundle\Entity\ChannelDescription
