parameters:
    sil_ecommerce.entity.product.class:                 LisemBundle\Entity\SilEcommerceBundle\Product
    sil_ecommerce.entity.order.class:                   LisemBundle\Entity\SilEcommerceBundle\Order
    sil_ecommerce.entity.product_variant.class:         LisemBundle\Entity\SilEcommerceBundle\ProductVariant
    sil_ecommerce.entity.product_option_value.class:    LisemBundle\Entity\SilEcommerceBundle\ProductOptionValue

    lisem.entity.channel_description.class:             LisemBundle\Entity\ChannelDescription
