lisem_not_implemented:
    path:   %sil.url_prefix%/not_implemented
    defaults: { _controller: LisemBundle:Default:notImplemented }

lisem_test_email:
    path:   %sil.url_prefix%/lisem_test_email
    defaults: { _controller: LisemBundle:Default:testEmail }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
