sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
        sil.email.block.emails_list: ~  # TODO: put this in Email bundle
#        sonata.admin.block.menu:
#
# sonata_admin:
#     show_mosaic_button: false
#     dashboard:
#         groups:
#
#             # ##################################################################
#             # CRM
#             # ##################################################################
#
#             lisem.menu.crm_contacts:
#                 label: lisem.menu_label.crm_contacts
#                 icon:  '<i class="fa fa-address-card"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_seed_batch_organism_list
#                       label: lisem.menu_label.organisms_list
#
#             lisem.menu.crm_emailing:
#                 label: lisem.menu_label.crm_emailing
#                 icon:  '<i class="fa fa-envelope-o"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_email_list
#                       label: lisem.menu_label.emailing_list
#
#             # ##################################################################
#             # VARIETIES
#             # ##################################################################
#
#             lisem.menu.species:
#                 label: lisem.menu_label.species
#                 icon:  '<i class="fa fa-pagelines"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_variety_species_list
#                       label: lisem.menu_label.species_list
#
#             lisem.menu.varieties:
#                 label: lisem.menu_label.varieties
#                 icon:  '<i class="fa fa-tree"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_variety_variety_list
#                       label: lisem.menu_label.varieties_list
#
#             # ##################################################################
#             # SEED BATCHES
#             # ##################################################################
#
#             lisem.menu.seedbatch:
#                 label: lisem.menu_label.seed_batches
#                 icon:  '<i class="fa fa-shopping-bag"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_seedbatch_seedbatch_list
#                       label: lisem.menu_label.seed_batches_list
#
#             lisem.menu.plot:
#                 label: lisem.menu_label.plot
#                 icon:  '<i class="fa fa-th"></i>'
#                 on_top: true
#                 items:
#                     - route: admin_seedbatch_plot_list
#                       label: lisem.menu_label.plots_list
#
#             # TEMPORARILY DISABLED
#             #
#             # lisem.menu.germination_tests:
#             #     label: lisem.menu_label.germination_tests
#             #     icon:  '<i class="fa fa-eyedropper"></i>'
#             #     on_top: true
#             #     items:
#             #         - label: lisem.menu_label.germination_tests
#             #           route: lisem_not_implemented
#
#             lisem.menu.producers:
#                 label: lisem.menu_label.producers
#                 icon:  '<i class="fa fa-user-circle"></i>'
#                 on_top: true
#                 items:
#                     - label: lisem.menu_label.producers_list
#                       route: admin_seed_batch_seedProducer_list
#
#             # ##################################################################
#             # PRODUCTS
#             # ##################################################################
#
#             lisem.menu.products:
#                 label: lisem.menu_label.products
#                 icon:  '<i class="fa fa-shopping-cart"></i>'
#                 items:
#                     - route: admin_sil_seeds_product_list
#                       label: lisem.menu_label.seed_products_list
#
#                     - label: lisem.menu_label.other_products_list
#                       route: admin_sil_other_product_list
#
#             # TEMPORARILY DISABLED
#             #
#             # lisem.menu.packagings:
#             #     label: lisem.menu_label.packagings
#             #     icon:  '<i class="fa fa-archive"></i>'
#             #     on_top: true
#             #     items:
#             #         - label: lisem.menu_label.packagings
#             #           route: lisem_not_implemented
#
#             # ##################################################################
#             # PRODUCTS
#             # ##################################################################
#
#             # TEMPORARILY DISABLED
#             #
#             # lisem.menu.inventory:
#             #     label: lisem.menu_label.inventory
#             #     icon:  '<i class="fa fa-list"></i>'
#             #     on_top: true
#             #     items:
#             #         - label: lisem.menu_label.inventory
#             #           route: lisem_not_implemented
#             #
#             # lisem.menu.catalogs:
#             #     label: lisem.menu_label.catalogs
#             #     icon:  '<i class="fa fa-book"></i>'
#             #     on_top: true
#             #     items:
#             #         - label: lisem.menu_label.catalogs
#             #           route: lisem_not_implemented
#
#             # ##################################################################
#             # ORDERS
#             # ##################################################################
#
#             lisem.menu.orders:
#                 label: lisem.menu_label.orders
#                 icon:  '<i class="fa fa-money"></i>'
#                 on_top: true
#                 items:
#                     - label: lisem.menu_label.orders_list
#                       route: admin_ecommerce_order_list
#                     # - label: lisem.menu_label.customers_list
#                     #   route: admin_sil_crm_customer_list
#
#
#             lisem.menu.accounting:
#                 label: lisem.menu_label.accounting
#                 icon:  '<i class="fa fa-balance-scale"></i>'
#                 items:
#                     - label: lisem.menu_label.sales_journal
#                       route: admin_ecommerce_sales_journal_list
#                     - label: lisem.menu_label.cash_book
#                       route: admin_ecommerce_payment_list
#
#             # sil.menu.stock:
#             #     label: sil.menu_label.stock_management
#             #     icon:  '<i class="fa fa-cubes"></i>'
#             #     items:
#             #         - label: sil.menu_label.items
#             #           route: admin_stock_item_list
#             #         - label: sil.menu_label.operations
#             #           route: admin_stock_operation_list
#             #         - label: sil.menu_label.movements
#             #           route: admin_stock_movement_list
#             #
#             # sil.menu.manufacturing:
#             #     label: sil.menu_label.manufacturing
#             #     icon:  '<i class="fa fa-industry"></i>'
#             #     items:
#             #         - label: sil.menu_label.bom
#             #           route: admin_manufacturing_bom_list
#
#             # App settings:
#             #     provider: parameters_sidebar_menu
#             #     icon:     '<i class="fa fa-sliders"></i>'
#
#     options:
#         use_icheck: true
#         confirm_exit: false
#         html5_validate: false
